// STEAL THE TECH — catalog source of truth.
// `npm run catalog` turns this into supabase/migrations/*_catalog.sql.
// All brands, names and artwork are original/fictional.

export const RARITIES = [
  // id, tier, label, color, value range [min,max], payback seconds (value / income),
  // steal penalty (chance), extra steal seconds, xp on find, expected supply (market model)
  { id: 'common',    tier: 1, label: 'COMMON',    color: '#a3aec2', range: [60, 260],               payback: 40,  stealPenalty: 0.00, stealExtra: 0, xp: 4,    expectedSupply: 400 },
  { id: 'uncommon',  tier: 2, label: 'UNCOMMON',  color: '#4ade80', range: [380, 1300],             payback: 55,  stealPenalty: 0.02, stealExtra: 0, xp: 10,   expectedSupply: 250 },
  { id: 'rare',      tier: 3, label: 'RARE',      color: '#38bdf8', range: [2200, 7500],            payback: 70,  stealPenalty: 0.05, stealExtra: 1, xp: 30,   expectedSupply: 120 },
  { id: 'epic',      tier: 4, label: 'EPIC',      color: '#a855f7', range: [13000, 48000],          payback: 85,  stealPenalty: 0.08, stealExtra: 1, xp: 80,   expectedSupply: 60 },
  { id: 'legendary', tier: 5, label: 'LEGENDARY', color: '#fbbf24', range: [95000, 340000],         payback: 105, stealPenalty: 0.12, stealExtra: 2, xp: 220,  expectedSupply: 30 },
  { id: 'mythic',    tier: 6, label: 'MYTHIC',    color: '#f43f5e', range: [650000, 2300000],       payback: 125, stealPenalty: 0.16, stealExtra: 3, xp: 600,  expectedSupply: 15 },
  { id: 'ultra',     tier: 7, label: 'ULTRA',     color: '#e879f9', range: [4800000, 16500000],     payback: 145, stealPenalty: 0.20, stealExtra: 4, xp: 1500, expectedSupply: 8 },
  { id: 'secret',    tier: 9, label: 'SECRET',    color: '#f8fafc', range: [36000000, 125000000],   payback: 170, stealPenalty: 0.25, stealExtra: 6, xp: 5000, expectedSupply: 4 },
  { id: 'limited',   tier: 8, label: 'LIMITED',   color: '#fb923c', range: [1500000, 42000000],     payback: 145, stealPenalty: 0.20, stealExtra: 4, xp: 2000, expectedSupply: 0 },
];

export const CATEGORIES = ['TECH', 'GAMING', 'CARS', 'FASHION', 'LUXURY', 'SPORTS'];

// Fictional brand palettes: [main color, accent color]
export const BRANDS = {
  NOVA: ['#22d3ee', '#0e7490'],
  VOLT: ['#facc15', '#a16207'],
  NEXUS: ['#a78bfa', '#5b21b6'],
  APEX: ['#f87171', '#991b1b'],
  ZENITH: ['#e2e8f0', '#475569'],
  QUANTUM: ['#2dd4bf', '#a21caf'],
  ORBIT: ['#60a5fa', '#1e40af'],
  PULSE: ['#f472b6', '#9d174d'],
  KRYO: ['#a5f3fc', '#0369a1'],
  LUMA: ['#fdba74', '#c2410c'],
  ONYX: ['#fbbf24', '#111827'],
  VERTEX: ['#a3e635', '#3f6212'],
};

// [rarity, category, kind, brand, name, extra?]
// extra: { value, maxSupply, droppable, tradeable, flavor, id }
export const ITEMS = [
  // ── starter (soulbound, never drops) ──
  ['common', 'TECH', 'tv', 'NOVA', 'NOVA 32" Starter TV', { id: 'nova-starter-tv', value: 150, income: 8, droppable: false, tradeable: false, flavor: 'Everyone starts somewhere. Yours forever.' }],

  // ── COMMON ──
  ['common', 'TECH', 'phone', 'VOLT', 'VOLT Pocket Phone'],
  ['common', 'TECH', 'tv', 'NOVA', 'NOVA 40" Basic TV'],
  ['common', 'TECH', 'camera', 'ORBIT', 'ORBIT Snap Cam'],
  ['common', 'TECH', 'speaker', 'PULSE', 'PULSE Mini Speaker'],
  ['common', 'TECH', 'tv', 'LUMA', 'LUMA 43" Smart TV'],
  ['common', 'TECH', 'tv', 'ORBIT', 'ORBIT 32" Kitchen TV'],
  ['common', 'GAMING', 'controller', 'VOLT', 'VOLT Pad Controller'],
  ['common', 'GAMING', 'keyboard', 'NEXUS', 'NEXUS Clicky Keyboard'],
  ['common', 'GAMING', 'monitor', 'APEX', 'APEX 24" Monitor'],
  ['common', 'GAMING', 'handheld', 'KRYO', 'KRYO Retro Handheld'],
  ['common', 'CARS', 'car', 'ZENITH', 'ZENITH City Hatch'],
  ['common', 'CARS', 'motorbike', 'VOLT', 'VOLT Scoot-E Moped'],
  ['common', 'CARS', 'car', 'PULSE', 'PULSE Dune Buggy'],
  ['common', 'CARS', 'car', 'ORBIT', 'ORBIT Compact Coupe'],
  ['common', 'FASHION', 'sneakers', 'VERTEX', 'VERTEX Canvas Sneakers'],
  ['common', 'FASHION', 'cap', 'LUMA', 'LUMA Logo Cap'],
  ['common', 'FASHION', 'hoodie', 'NOVA', 'NOVA Basic Hoodie'],
  ['common', 'FASHION', 'sunglasses', 'ORBIT', 'ORBIT Shades'],
  ['common', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Steel Watch'],
  ['common', 'LUXURY', 'chain', 'ONYX', 'ONYX Silver Chain'],
  ['common', 'LUXURY', 'perfume', 'LUMA', 'LUMA Cologne No.1'],
  ['common', 'SPORTS', 'ball', 'PULSE', 'PULSE Street Ball'],
  ['common', 'SPORTS', 'skateboard', 'VERTEX', 'VERTEX Cruiser Board'],
  ['common', 'SPORTS', 'racket', 'APEX', 'APEX Club Racket'],
  ['common', 'SPORTS', 'bicycle', 'KRYO', 'KRYO Trail Bike'],

  // ── UNCOMMON ──
  ['uncommon', 'TECH', 'tv', 'NOVA', 'NOVA 55" 4K TV'],
  ['uncommon', 'TECH', 'tv', 'VOLT', 'VOLT 50" Neon TV'],
  ['uncommon', 'TECH', 'tv', 'ZENITH', 'ZENITH 48" Gallery TV'],
  ['uncommon', 'TECH', 'tablet', 'VOLT', 'VOLT Tab 11'],
  ['uncommon', 'TECH', 'headphones', 'NEXUS', 'NEXUS Buds Pro'],
  ['uncommon', 'TECH', 'laptop', 'ORBIT', 'ORBIT Air Laptop'],
  ['uncommon', 'TECH', 'smartwatch', 'NEXUS', 'NEXUS Fit Watch'],
  ['uncommon', 'GAMING', 'monitor', 'APEX', 'APEX 27" Gaming Monitor'],
  ['uncommon', 'GAMING', 'console', 'VOLT', 'VOLT Switchback Console'],
  ['uncommon', 'GAMING', 'keyboard', 'KRYO', 'KRYO RGB Keyboard'],
  ['uncommon', 'GAMING', 'controller', 'NEXUS', 'NEXUS Pro Controller'],
  ['uncommon', 'CARS', 'car', 'VOLT', 'VOLT E-Hatch'],
  ['uncommon', 'CARS', 'motorbike', 'APEX', 'APEX Street Bike'],
  ['uncommon', 'CARS', 'sports_car', 'ZENITH', 'ZENITH Sport Coupe'],
  ['uncommon', 'FASHION', 'jacket', 'KRYO', 'KRYO Puffer Jacket'],
  ['uncommon', 'FASHION', 'sneakers', 'VERTEX', 'VERTEX Runner Sneakers'],
  ['uncommon', 'FASHION', 'backpack', 'ORBIT', 'ORBIT Tech Backpack'],
  ['uncommon', 'FASHION', 'cap', 'PULSE', 'PULSE Snapback'],
  ['uncommon', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Gold-Tone Watch'],
  ['uncommon', 'LUXURY', 'ring', 'ONYX', 'ONYX Signet Ring'],
  ['uncommon', 'LUXURY', 'perfume', 'LUMA', 'LUMA Eau de Neon'],
  ['uncommon', 'SPORTS', 'ball', 'APEX', 'APEX Pro Football'],
  ['uncommon', 'SPORTS', 'racket', 'PULSE', 'PULSE Carbon Racket'],
  ['uncommon', 'SPORTS', 'skateboard', 'VERTEX', 'VERTEX Park Skateboard'],
  ['uncommon', 'SPORTS', 'surfboard', 'KRYO', 'KRYO Surfboard'],

  // ── RARE ──
  ['rare', 'TECH', 'tv', 'NOVA', 'NOVA 65" QLED TV'],
  ['rare', 'TECH', 'tv', 'LUMA', 'LUMA 58" Frame TV'],
  ['rare', 'TECH', 'phone', 'QUANTUM', 'QUANTUM Fold Phone'],
  ['rare', 'TECH', 'camera', 'ORBIT', 'ORBIT Mirrorless Cam'],
  ['rare', 'TECH', 'speaker', 'PULSE', 'PULSE Tower Speaker'],
  ['rare', 'GAMING', 'laptop', 'NEXUS', 'NEXUS Gaming Laptop'],
  ['rare', 'GAMING', 'gpu', 'APEX', 'APEX Titan GPU'],
  ['rare', 'GAMING', 'vr_headset', 'VOLT', 'VOLT VR Lite'],
  ['rare', 'GAMING', 'handheld', 'QUANTUM', 'QUANTUM Handheld X'],
  ['rare', 'CARS', 'sports_car', 'APEX', 'APEX Roadster'],
  ['rare', 'CARS', 'suv', 'ZENITH', 'ZENITH Electric SUV'],
  ['rare', 'CARS', 'motorbike', 'VOLT', 'VOLT Cafe Racer'],
  ['rare', 'FASHION', 'sneakers', 'VERTEX', 'VERTEX Hi-Top Sneakers'],
  ['rare', 'FASHION', 'jacket', 'NOVA', 'NOVA Reflective Jacket'],
  ['rare', 'FASHION', 'sunglasses', 'ONYX', 'ONYX Designer Shades'],
  ['rare', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Diver Watch'],
  ['rare', 'LUXURY', 'chain', 'ONYX', 'ONYX Gold Chain'],
  ['rare', 'LUXURY', 'perfume', 'LUMA', 'LUMA Crystal Perfume'],
  ['rare', 'SPORTS', 'bicycle', 'PULSE', 'PULSE Pro Road Bike'],
  ['rare', 'SPORTS', 'golf', 'APEX', 'APEX Golf Driver'],
  ['rare', 'SPORTS', 'surfboard', 'KRYO', 'KRYO Pro Surfboard'],
  ['rare', 'SPORTS', 'skateboard', 'VERTEX', 'VERTEX Signature Deck'],

  // ── EPIC ──
  ['epic', 'TECH', 'tv', 'NOVA', 'NOVA 75" OLED TV'],
  ['epic', 'TECH', 'tv', 'LUMA', 'LUMA 77" Theater TV'],
  ['epic', 'TECH', 'phone', 'QUANTUM', 'QUANTUM Pro Phone'],
  ['epic', 'TECH', 'tablet', 'ORBIT', 'ORBIT Cinema Tablet'],
  ['epic', 'TECH', 'headphones', 'NEXUS', 'NEXUS Studio Headphones'],
  ['epic', 'GAMING', 'gaming_pc', 'NEXUS', 'NEXUS Epic Gaming PC'],
  ['epic', 'GAMING', 'monitor', 'APEX', 'APEX 49" Ultrawide'],
  ['epic', 'GAMING', 'controller', 'VOLT', 'VOLT Elite Controller'],
  ['epic', 'GAMING', 'gpu', 'KRYO', 'KRYO Liquid GPU'],
  ['epic', 'CARS', 'sports_car', 'APEX', 'APEX GT Coupe'],
  ['epic', 'CARS', 'suv', 'ZENITH', 'ZENITH Luxury SUV'],
  ['epic', 'CARS', 'motorbike', 'VOLT', 'VOLT Superbike'],
  ['epic', 'FASHION', 'sneakers', 'VERTEX', 'VERTEX Glow Sneakers'],
  ['epic', 'FASHION', 'jacket', 'KRYO', 'KRYO Designer Parka'],
  ['epic', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Chronograph'],
  ['epic', 'LUXURY', 'diamond', 'ONYX', 'ONYX Diamond Studs'],
  ['epic', 'LUXURY', 'perfume', 'LUMA', 'LUMA Parfum Royale'],
  ['epic', 'SPORTS', 'bicycle', 'PULSE', 'PULSE Carbon Race Bike'],
  ['epic', 'SPORTS', 'ball', 'APEX', 'APEX Signature Ball'],
  ['epic', 'SPORTS', 'golf', 'KRYO', 'KRYO Pro Golf Set'],

  // ── LEGENDARY ──
  ['legendary', 'TECH', 'tv', 'QUANTUM', 'QUANTUM OLED 85"'],
  ['legendary', 'TECH', 'camera', 'NOVA', 'NOVA Pro Camera Rig'],
  ['legendary', 'TECH', 'drone', 'ORBIT', 'ORBIT Sky Drone'],
  ['legendary', 'GAMING', 'gaming_pc', 'NEXUS', 'NEXUS Legendary Gaming PC'],
  ['legendary', 'GAMING', 'console', 'VOLT', 'VOLT Pro Console Elite'],
  ['legendary', 'GAMING', 'monitor', 'APEX', 'APEX 4K 240Hz Monitor'],
  ['legendary', 'CARS', 'supercar', 'APEX', 'APEX Supercar S'],
  ['legendary', 'CARS', 'sports_car', 'ZENITH', 'ZENITH Grand Tourer'],
  ['legendary', 'CARS', 'motorbike', 'VOLT', 'VOLT Track Bike'],
  ['legendary', 'FASHION', 'sneakers', 'VERTEX', 'VERTEX Golden Kicks'],
  ['legendary', 'FASHION', 'jacket', 'ONYX', 'ONYX Couture Jacket'],
  ['legendary', 'FASHION', 'backpack', 'NOVA', 'NOVA Holo Backpack'],
  ['legendary', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Tourbillon'],
  ['legendary', 'LUXURY', 'chain', 'ONYX', 'ONYX Diamond Chain'],
  ['legendary', 'LUXURY', 'gold_bar', 'LUMA', 'LUMA Gold Bar Set'],
  ['legendary', 'SPORTS', 'ball', 'PULSE', 'PULSE Championship Ball'],
  ['legendary', 'SPORTS', 'bicycle', 'KRYO', 'KRYO Titanium Bike'],
  ['legendary', 'SPORTS', 'racket', 'APEX', 'APEX Golden Racket'],

  // ── MYTHIC ──
  ['mythic', 'TECH', 'tv', 'NOVA', 'NOVA Ultra OLED 98"'],
  ['mythic', 'TECH', 'phone', 'QUANTUM', 'QUANTUM Fold X Phone'],
  ['mythic', 'TECH', 'camera', 'ORBIT', 'ORBIT Cinema Cam 12K'],
  ['mythic', 'GAMING', 'gaming_pc', 'QUANTUM', 'QUANTUM Gaming PC'],
  ['mythic', 'GAMING', 'gaming_setup', 'NEXUS', 'NEXUS Command Center'],
  ['mythic', 'GAMING', 'controller', 'VOLT', 'VOLT Phantom Controller'],
  ['mythic', 'CARS', 'supercar', 'APEX', 'APEX GT Supercar'],
  ['mythic', 'CARS', 'hypercar', 'ZENITH', 'ZENITH Hyper GT'],
  ['mythic', 'FASHION', 'jacket', 'VERTEX', 'VERTEX Aurora Jacket'],
  ['mythic', 'FASHION', 'sneakers', 'KRYO', 'KRYO Crystal Sneakers'],
  ['mythic', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Skeleton Watch'],
  ['mythic', 'LUXURY', 'diamond', 'ONYX', 'ONYX Emerald Diamond'],
  ['mythic', 'SPORTS', 'skateboard', 'KRYO', 'KRYO Hoverboard'],
  ['mythic', 'SPORTS', 'trophy', 'PULSE', 'PULSE Golden Trophy'],

  // ── ULTRA ──
  ['ultra', 'TECH', 'tv', 'QUANTUM', 'QUANTUM Holo Wall 150"'],
  ['ultra', 'TECH', 'drone', 'NOVA', 'NOVA Stratos Drone'],
  ['ultra', 'GAMING', 'gaming_pc', 'NEXUS', 'NEXUS Titan Rig X'],
  ['ultra', 'GAMING', 'vr_headset', 'VOLT', 'VOLT Aurora VR Pro'],
  ['ultra', 'GAMING', 'gpu', 'KRYO', 'KRYO Frostbite GPU'],
  ['ultra', 'CARS', 'hypercar', 'APEX', 'APEX Vortex Hypercar'],
  ['ultra', 'CARS', 'motorbike', 'PULSE', 'PULSE Neon Superbike'],
  ['ultra', 'FASHION', 'sneakers', 'VERTEX', 'VERTEX Diamond Kicks'],
  ['ultra', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Royal Tourbillon'],
  ['ultra', 'LUXURY', 'chain', 'ONYX', 'ONYX Crown Chain'],
  ['ultra', 'SPORTS', 'trophy', 'PULSE', 'PULSE Platinum Trophy'],

  // ── SECRET (supply-capped, server-wide announcement when found) ──
  ['secret', 'TECH', 'tv', 'QUANTUM', 'QUANTUM 120" VOID OLED', { value: 95000000, maxSupply: 10, flavor: 'A screen so black it swallows light. Ten were ever made.' }],
  ['secret', 'TECH', 'phone', 'APEX', 'ZERO-LAG FUTURE PHONE', { value: 48000000, maxSupply: 10, flavor: 'Replies before you finish typing.' }],
  ['secret', 'GAMING', 'monitor', 'NOVA', 'NOVA HYPER DISPLAY', { value: 62000000, maxSupply: 10, flavor: 'Refresh rate: yes.' }],
  ['secret', 'GAMING', 'gaming_setup', 'NEXUS', 'INFINITE GAMING SETUP', { value: 120000000, maxSupply: 10, flavor: 'The final form of the battlestation.' }],
  ['secret', 'GAMING', 'console', 'VOLT', 'PHANTOM PROTOTYPE CONSOLE', { value: 72000000, maxSupply: 10, flavor: 'Never announced. Never released. Somehow here.' }],
  ['secret', 'CARS', 'hypercar', 'ZENITH', 'ZENITH ECLIPSE HYPERCAR', { value: 125000000, maxSupply: 5, flavor: 'Only five exist. It is very fast and very stealable.' }],
  ['secret', 'LUXURY', 'diamond', 'ONYX', 'ONYX SINGULARITY DIAMOND', { value: 110000000, maxSupply: 5, flavor: 'Heavier than it should be.' }],
  ['secret', 'FASHION', 'sneakers', 'KRYO', 'KRYO ZERO-G SNEAKERS', { value: 40000000, maxSupply: 10, flavor: 'Laces optional. Gravity optional.' }],
  ['secret', 'SPORTS', 'ball', 'PULSE', 'PULSE INFINITY BALL', { value: 38000000, maxSupply: 10, flavor: 'Never lands out.' }],

  // ── LIMITED (hard supply cap, serial numbered) ──
  ['limited', 'TECH', 'tv', 'NOVA', 'PHANTOM TV', { id: 'phantom-tv', value: 2600000, maxSupply: 100, flavor: 'Limited run of 100. Look for the serial.' }],
  ['limited', 'GAMING', 'console', 'VOLT', 'VOLT Aurora Console LTD', { value: 1600000, maxSupply: 250 }],
  ['limited', 'GAMING', 'gpu', 'QUANTUM', 'QUANTUM Founders GPU', { value: 6200000, maxSupply: 75 }],
  ['limited', 'CARS', 'hypercar', 'APEX', 'APEX Midnight Hypercar', { value: 42000000, maxSupply: 25 }],
  ['limited', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Chrono Gold LTD', { value: 12500000, maxSupply: 50 }],
  ['limited', 'FASHION', 'sneakers', 'VERTEX', 'VERTEX Genesis Sneakers', { value: 2100000, maxSupply: 150 }],
  ['limited', 'TECH', 'drone', 'ORBIT', 'ORBIT Moonshot Drone', { value: 3100000, maxSupply: 120 }],
  ['limited', 'SPORTS', 'trophy', 'PULSE', "PULSE '26 Championship Trophy", { value: 8400000, maxSupply: 60 }],

  // ── EVENT exclusives (only from Event Drops and 7-day streak rewards) ──
  ['epic', 'GAMING', 'headphones', 'NOVA', 'NOVA Festival Headset', { event: true }],
  ['epic', 'CARS', 'car', 'APEX', 'APEX Rally Kart', { event: true }],
  ['epic', 'FASHION', 'hoodie', 'VERTEX', 'VERTEX Hype Hoodie', { event: true }],
  ['legendary', 'SPORTS', 'skateboard', 'VOLT', 'VOLT Streak Hoverboard', { event: true }],
  ['legendary', 'LUXURY', 'luxury_watch', 'ZENITH', 'ZENITH Gala Watch', { event: true }],
  ['legendary', 'TECH', 'speaker', 'QUANTUM', 'QUANTUM Boom Box', { event: true }],
];

// Drop machines. Weights are percentages per rarity. Price is derived from the
// catalog's expected value (see gen-catalog.mjs) so resale can never out-earn the price.
export const DROPS = [
  { id: 'basic',   name: 'BASIC DROP',   minLevel: 1,  requiresKey: false, eventOnly: false, xp: 12,  priceFactor: 1.00,
    description: 'Cheap and cheerful. Mostly Common & Uncommon.',
    weights: { common: 70, uncommon: 24, rare: 5.2, epic: 0.7, legendary: 0.1 } },
  { id: 'premium', name: 'PREMIUM DROP', minLevel: 3,  requiresKey: false, eventOnly: false, xp: 30,  priceFactor: 1.00,
    description: 'Better odds of Rare and Epic tech.',
    weights: { common: 8, uncommon: 42, rare: 38, epic: 10.5, legendary: 1.4, mythic: 0.1 } },
  { id: 'elite',   name: 'ELITE DROP',   minLevel: 8,  requiresKey: false, eventOnly: false, xp: 80,  priceFactor: 1.00,
    description: 'Serious odds of Legendary and Mythic.',
    weights: { rare: 20, epic: 45, legendary: 28, mythic: 6, ultra: 0.9, limited: 0.1 } },
  { id: 'ultra',   name: 'ULTRA DROP',   minLevel: 15, requiresKey: false, eventOnly: false, xp: 200, priceFactor: 1.00,
    description: 'Where Ultra items live. Secrets have been seen.',
    weights: { legendary: 35, mythic: 45, ultra: 16, limited: 2.8, secret: 1.2 } },
  { id: 'event',   name: 'EVENT DROP',   minLevel: 3,  requiresKey: false, eventOnly: true,  xp: 60,  priceFactor: 1.00,
    description: 'Only during live events. Themed items + event exclusives.',
    weights: { uncommon: 20, rare: 40, epic: 28, legendary: 10, mythic: 2 } },
  { id: 'secret',  name: 'SECRET DROP',  minLevel: 20, requiresKey: true,  eventOnly: false, xp: 600, priceFactor: 1.00,
    description: 'Requires a Secret Key. The best odds in the game.',
    weights: { mythic: 30, ultra: 50, limited: 8, secret: 12 } },
];

// kind: base (slots), security, vault. level → [cost, value, name]
export const UPGRADES = {
  base: [
    [1, 0, 4, 'Starter Garage'],
    [2, 3000, 8, 'Tech Loft'],
    [3, 40000, 12, 'Neon Warehouse'],
    [4, 500000, 16, 'Collector Hall'],
    [5, 6000000, 24, 'Tech Mansion'],
    [6, 80000000, 32, 'Sky Vault Tower'],
    [7, 1000000000, 40, 'Mega Complex'],
    [8, 15000000000, 50, 'Tech Megaplex'],
  ],
  security: [
    [1, 0, 1, 'Basic Alarm'],
    [2, 6000, 2, 'Camera'],
    [3, 75000, 3, 'Security Door'],
    [4, 900000, 4, 'Advanced Scanner'],
    [5, 12000000, 5, 'Elite Security'],
    [6, 150000000, 6, 'Quantum Security'],
  ],
  vault: [
    [1, 0, 3, 'Lockbox'],
    [2, 5000, 5, 'Safe'],
    [3, 60000, 10, 'Vault Room'],
    [4, 750000, 15, 'Bank Vault'],
    [5, 9000000, 25, 'Titan Vault'],
    [6, 110000000, 40, 'Quantum Vault'],
  ],
};

export const QUESTS = [
  // id, period, title, metric, target, reward
  ['d_open5', 'daily', 'Open 5 drops', 'open_drops', 5, { cash: 4000, income_secs: 240, xp: 120, tokens: { basic: 1 } }],
  ['d_earn50k', 'daily', 'Earn $50,000', 'earn_cash', 50000, { cash: 6000, income_secs: 300, xp: 150 }],
  ['d_raid3', 'daily', 'Raid 3 players', 'raid_players', 3, { cash: 5000, income_secs: 300, xp: 180, tokens: { basic: 1 } }],
  ['d_sell1', 'daily', 'Sell an item', 'sell_item', 1, { cash: 2500, income_secs: 120, xp: 80 }],
  ['d_rare', 'daily', 'Find a Rare', 'find_rare', 1, { cash: 3000, income_secs: 180, xp: 100 }],
  ['d_legend', 'daily', 'Find a Legendary', 'find_legendary', 1, { cash: 20000, income_secs: 600, xp: 400, tokens: { premium: 1 } }],
  ['w_mythic', 'weekly', 'Find a Mythic', 'find_mythic', 1, { cash: 250000, income_secs: 1800, xp: 2000, secret_keys: 1 }],
  ['w_trades20', 'weekly', 'Complete 20 trades (direct or market)', 'complete_trades', 20, { cash: 150000, income_secs: 1800, xp: 1500, tokens: { elite: 1 } }],
  ['w_tvs10', 'weekly', 'Collect 10 different TVs', 'collect_tvs', 10, { cash: 100000, income_secs: 1200, xp: 1200, tokens: { premium: 2 }, cosmetic: 'plat-screenwall' }],
];

export const ACHIEVEMENTS = [
  // id, title, description, icon, xp, cash
  ['first_drop', 'Unboxed', 'Open your first drop', '📦', 50, 500],
  ['first_rare', 'Blue Glow', 'Find a Rare item', '💠', 80, 1000],
  ['first_epic', 'Purple Haze', 'Find an Epic item', '🟣', 150, 5000],
  ['first_legendary', 'Golden Hour', 'Find a Legendary item', '🌟', 400, 25000],
  ['first_mythic', 'Myth Made Real', 'Find a Mythic item', '🔥', 1000, 150000],
  ['first_ultra', 'Beyond Ultra', 'Find an Ultra item', '🌈', 2500, 1000000],
  ['first_secret', 'SECRET DISCOVERED', 'Find a Secret item', '🕳️', 8000, 5000000],
  ['first_limited', 'Numbered', 'Own a Limited item', '🔢', 2000, 500000],
  ['first_steal', 'Sticky Fingers', 'Steal your first item', '🥷', 100, 2000],
  ['steal_10', 'Cat Burglar', 'Steal 10 items', '🐈‍⬛', 500, 50000],
  ['steal_50', 'Master Thief', 'Steal 50 items', '💰', 3000, 2000000],
  ['defend_1', 'Not Today', 'Stop a raid on your base', '🛡️', 100, 3000],
  ['defend_10', 'Fortress', 'Stop 10 raids', '🏰', 800, 100000],
  ['first_trade', 'Deal!', 'Complete a trade', '🤝', 100, 2000],
  ['trade_20', 'Wheeler Dealer', 'Complete 20 trades', '📈', 800, 100000],
  ['first_sale', 'Open for Business', 'Sell an item on the market', '🏷️', 60, 1000],
  ['base_3', 'Moving Up', 'Upgrade your base to Level 3', '🏠', 200, 5000],
  ['base_5', 'Mansion Life', 'Upgrade your base to Level 5', '🏛️', 2000, 500000],
  ['security_4', 'Locked Down', 'Reach Security Level 4', '🔐', 800, 50000],
  ['security_6', 'Quantum Locked', 'Reach Security Level 6', '⚛️', 5000, 5000000],
  ['collect_25', 'Collector', 'Discover 25 different items', '📚', 400, 20000],
  ['collect_75', 'Archivist', 'Discover 75 different items', '🗂️', 2500, 1000000],
  ['category_complete', 'Completionist', 'Complete a whole collection category', '🏆', 5000, 5000000],
  ['millionaire', 'Millionaire', 'Hold $1,000,000 cash', '💵', 500, 0],
  ['billionaire', 'Billionaire', 'Hold $1,000,000,000 cash', '💎', 5000, 0],
  ['level_10', 'Trader', 'Reach Level 10', '🔟', 0, 50000],
  ['level_25', 'Mastermind', 'Reach Level 25', '🧠', 0, 2500000],
  ['prestige_1', 'Reborn', 'Prestige for the first time', '✨', 0, 0],
  ['streak_7', 'Seven Day Streak', 'Claim 7 daily rewards in a row', '📅', 500, 25000],
];

// Cosmetics never change stats.
export const COSMETICS = [
  // id, slot, name, price, unlock, data
  ['theme-neon', 'theme', 'Neon Night', 0, null, { floor: '#131a2e', wall: '#1e293b', glow: '#22d3ee' }],
  ['theme-garage', 'theme', 'Cyber Garage', 15000, null, { floor: '#1c1917', wall: '#292524', glow: '#f97316' }],
  ['theme-arctic', 'theme', 'Arctic Lab', 60000, null, { floor: '#0f2230', wall: '#164e63', glow: '#a5f3fc' }],
  ['theme-sakura', 'theme', 'Sakura Studio', 250000, null, { floor: '#2a1522', wall: '#4a1d3a', glow: '#f9a8d4' }],
  ['theme-gold', 'theme', 'Gold Vault', 2500000, null, { floor: '#241c0b', wall: '#3f2f0c', glow: '#fbbf24' }],
  ['theme-void', 'theme', 'Void', 0, 'prestige:1', { floor: '#05030a', wall: '#140a24', glow: '#c084fc' }],
  ['theme-prestige', 'theme', 'Prestige Platinum', 0, 'prestige:2', { floor: '#1a1d24', wall: '#2d3340', glow: '#e2e8f0' }],
  ['floor-grid', 'floor', 'Glow Grid', 0, null, { pattern: 'grid' }],
  ['floor-hex', 'floor', 'Hex Tiles', 8000, null, { pattern: 'hex' }],
  ['floor-checker', 'floor', 'Race Checker', 30000, null, { pattern: 'checker' }],
  ['floor-marble', 'floor', 'Dark Marble', 400000, null, { pattern: 'marble' }],
  ['wall-panel', 'wall', 'Tech Panels', 0, null, { pattern: 'panel' }],
  ['wall-brick', 'wall', 'Neon Brick', 10000, null, { pattern: 'brick' }],
  ['wall-glass', 'wall', 'Glass Wall', 120000, null, { pattern: 'glass' }],
  ['light-cyan', 'lighting', 'Cyan Lights', 0, null, { color: '#22d3ee' }],
  ['light-magenta', 'lighting', 'Magenta Lights', 5000, null, { color: '#e879f9' }],
  ['light-lime', 'lighting', 'Toxic Lime', 5000, null, { color: '#a3e635' }],
  ['light-rainbow', 'lighting', 'Rainbow Cycle', 0, 'level:15', { color: 'rainbow' }],
  ['plat-basic', 'platform', 'Steel Pads', 0, null, { style: 'basic' }],
  ['plat-glass', 'platform', 'Glass Plinths', 20000, null, { style: 'glass' }],
  ['plat-holo', 'platform', 'Holo Rings', 300000, null, { style: 'holo' }],
  ['plat-screenwall', 'platform', 'Screen Wall', 0, 'quest', { style: 'screen' }],
  ['trail-none', 'trail', 'No Trail', 0, null, { style: 'none' }],
  ['trail-spark', 'trail', 'Sparks', 3000, null, { style: 'spark', color: '#fde047' }],
  ['trail-cash', 'trail', 'Cash Trail', 50000, null, { style: 'cash', color: '#4ade80' }],
  ['trail-glitch', 'trail', 'Glitch', 0, 'level:10', { style: 'glitch', color: '#22d3ee' }],
  ['trail-comet', 'trail', 'Comet', 0, 'prestige:1', { style: 'comet', color: '#c084fc' }],
  ['name-default', 'nameplate', 'Standard', 0, null, { style: 'default' }],
  ['name-neon', 'nameplate', 'Neon Tag', 7500, null, { style: 'neon' }],
  ['name-gold', 'nameplate', 'Gold Tag', 900000, null, { style: 'gold' }],
  ['name-legend', 'nameplate', 'Tech Legend', 0, 'level:50', { style: 'legend' }],
  ['emote-wave', 'emote', 'Wave 👋', 0, null, { emoji: '👋' }],
  ['emote-flex', 'emote', 'Flex 💪', 0, null, { emoji: '💪' }],
  ['emote-lol', 'emote', 'LOL 😂', 2000, null, { emoji: '😂' }],
  ['emote-money', 'emote', 'Make It Rain 💸', 25000, null, { emoji: '💸' }],
  ['emote-ninja', 'emote', 'Ninja 🥷', 0, 'level:5', { emoji: '🥷' }],
  ['emote-crown', 'emote', 'Crown 👑', 0, 'prestige:1', { emoji: '👑' }],
  ['anim-sparkle', 'item_fx', 'Sparkle Items', 150000, null, { style: 'sparkle' }],
  ['anim-orbit', 'item_fx', 'Orbiting Rings', 1500000, null, { style: 'orbit' }],
];

export const EVENT_TYPES = [
  // id, title, icon, description, category, price_mult, demand_boost, income_mult, luck_mult, weight
  ['tech_boom', 'TECH BOOM', '🔥', 'Technology demand is surging. TECH items are worth more and earn +25%.', 'TECH', 1.30, 30, 1.25, 1, 3],
  ['car_week', 'CAR WEEK', '🚗', 'Vehicle demand is up. CARS are worth more and earn +25%.', 'CARS', 1.35, 30, 1.25, 1, 3],
  ['gaming_fest', 'GAMING FESTIVAL', '🎮', 'Gaming items become more valuable and earn +25%.', 'GAMING', 1.30, 30, 1.25, 1, 3],
  ['fashion_week', 'FASHION WEEK', '👟', 'Fashion items are the talk of the town.', 'FASHION', 1.30, 30, 1.25, 1, 2],
  ['secret_hunt', 'SECRET HUNT', '💎', 'Rare items become far more discoverable. Mythic+ luck x2.5!', null, 1.00, 0, 1.00, 2.5, 2],
  ['market_crash', 'MARKET CRASH', '📉', 'Panic selling! One category is temporarily worth much less.', '*', 0.70, -30, 1.00, 1, 2],
];

export const LEVEL_TITLES = [
  [1, 'Rookie'], [3, 'Scavenger'], [5, 'Collector'], [8, 'Dealer'], [10, 'Trader'], [15, 'Hustler'],
  [20, 'Raider'], [25, 'Mastermind'], [30, 'Tycoon'], [40, 'Kingpin'], [50, 'Tech Legend'],
];

// NPC players ("bots"). They are clearly labelled as NPCs in the UI.
export const BOTS = [
  // name, style, base, security, vault, item plan (rarities), defend chance, extra item ids, cash
  { name: 'RookieRick', style: 'rookie', base: 1, security: 1, vault: 1, plan: ['common', 'common', 'uncommon', 'common'], defend: 0.05, cash: 800, tutorial: true,
    bio: 'Just moved in. Leaves the door open.' },
  { name: 'PixelPip', style: 'rookie', base: 2, security: 1, vault: 1, plan: ['common', 'uncommon', 'uncommon', 'rare', 'common', 'uncommon'], defend: 0.15, cash: 3000,
    bio: 'Collects anything that glows.' },
  { name: 'ByteBandit', style: 'raider', base: 2, security: 2, vault: 2, plan: ['uncommon', 'rare', 'rare', 'uncommon', 'rare', 'epic'], defend: 0.25, cash: 12000,
    bio: 'Steals first, asks never.' },
  { name: 'GlitchGoblin', style: 'collector', base: 3, security: 2, vault: 2, plan: ['rare', 'rare', 'epic', 'uncommon', 'rare', 'epic', 'rare', 'uncommon'], defend: 0.25, cash: 40000,
    bio: 'Hoards glitchy gadgets.' },
  { name: 'VoltVixen', style: 'trader', base: 3, security: 3, vault: 3, plan: ['rare', 'epic', 'epic', 'rare', 'legendary', 'rare', 'epic', 'rare'], defend: 0.3, cash: 150000,
    bio: 'Buys low. Sells to you.' },
  { name: 'NeonVandal', style: 'raider', base: 3, security: 3, vault: 2, plan: ['epic', 'epic', 'rare', 'legendary', 'epic', 'rare', 'epic', 'epic', 'rare'], defend: 0.3, cash: 120000,
    bio: 'Tags every base they rob.' },
  { name: 'ChromeCobra', style: 'raider', base: 4, security: 4, vault: 3, plan: ['legendary', 'epic', 'legendary', 'epic', 'mythic', 'epic', 'legendary', 'rare', 'epic', 'legendary'], defend: 0.35, cash: 900000,
    bio: 'Strikes fast. Never misses twice.' },
  { name: 'ZeroLagZed', style: 'trader', base: 4, security: 4, vault: 4, plan: ['legendary', 'legendary', 'epic', 'mythic', 'epic', 'legendary', 'epic', 'rare', 'legendary'], defend: 0.35, cash: 1200000,
    bio: 'Market maker. Always has a deal.' },
  { name: 'TechGhost', style: 'whale', base: 4, security: 4, vault: 3, plan: ['mythic', 'legendary', 'legendary', 'epic', 'mythic', 'legendary', 'epic', 'legendary'], defend: 0.4, cash: 5000000,
    extra: ['quantum-120-void-oled'], bio: 'Nobody knows how they got that TV.' },
  { name: 'NovaKnight', style: 'collector', base: 5, security: 5, vault: 4, plan: ['mythic', 'mythic', 'legendary', 'legendary', 'mythic', 'epic', 'legendary', 'mythic', 'legendary', 'epic', 'legendary', 'mythic'], defend: 0.4, cash: 15000000,
    extra: ['phantom-tv'], bio: 'Guards a museum of the finest tech.' },
  { name: 'QuantumQueen', style: 'whale', base: 5, security: 5, vault: 5, plan: ['ultra', 'mythic', 'mythic', 'legendary', 'mythic', 'ultra', 'legendary', 'mythic', 'legendary', 'mythic', 'legendary', 'legendary'], defend: 0.45, cash: 60000000,
    bio: 'Rules the leaderboards.' },
  { name: 'ApexAce', style: 'whale', base: 6, security: 6, vault: 5, plan: ['ultra', 'ultra', 'mythic', 'mythic', 'mythic', 'legendary', 'ultra', 'mythic', 'mythic', 'legendary', 'mythic', 'ultra', 'mythic', 'legendary'], defend: 0.5, cash: 250000000,
    extra: ['infinite-gaming-setup'], bio: 'Quantum security. Quantum ego.' },
];
