// Generates supabase/migrations/20260922000002_catalog.sql from catalog-data.mjs.
// Also prints the expected value of every drop so the economy stays honest:
// a drop's price is set at (or above) the average market value of what it gives,
// so opening drops and instantly reselling can never be a money printer.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  RARITIES, BRANDS, ITEMS, DROPS, UPGRADES, QUESTS, ACHIEVEMENTS, COSMETICS,
  EVENT_TYPES, LEVEL_TITLES, BOTS,
} from './catalog-data.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '..', 'supabase', 'migrations', '20260922000002_catalog.sql');

export const slug = (s) => s.toLowerCase().replace(/["'’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

function hash01(str) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
  return ((h >>> 0) % 10007) / 10006;
}

export function nice(n, sig = 2) {
  if (n < 10) return Math.max(1, Math.round(n));
  const p = Math.pow(10, Math.floor(Math.log10(n)) - (sig - 1));
  return Math.round(n / p) * p;
}

const R = Object.fromEntries(RARITIES.map((r) => [r.id, r]));

export function buildItems() {
  const seen = new Set();
  return ITEMS.map(([rarity, category, kind, brand, name, extra = {}], i) => {
    const r = R[rarity];
    if (!r) throw new Error(`bad rarity ${rarity}`);
    if (!BRANDS[brand]) throw new Error(`bad brand ${brand}`);
    const id = extra.id || slug(name);
    if (seen.has(id)) throw new Error(`duplicate id ${id}`);
    seen.add(id);
    const [lo, hi] = r.range;
    const t = hash01(id);
    const value = extra.value ?? nice(lo * Math.pow(hi / lo, t));
    const income = extra.income ?? nice(value / r.payback);
    const [color, accent] = BRANDS[brand];
    return {
      id, name, brand, kind, category, rarity, value, income,
      maxSupply: extra.maxSupply ?? null,
      tradeable: extra.tradeable ?? true,
      droppable: extra.droppable ?? !extra.event,
      eventOnly: !!extra.event,
      color, accent,
      flavor: extra.flavor ?? '',
      sort: i,
    };
  });
}

export function dropEV(drop, items) {
  let ev = 0;
  let total = 0;
  for (const [rarity, w] of Object.entries(drop.weights)) total += w;
  for (const [rarity, w] of Object.entries(drop.weights)) {
    let pool = items.filter((it) => it.rarity === rarity && (drop.eventOnly ? (it.droppable || it.eventOnly) : it.droppable));
    if (!pool.length) throw new Error(`empty pool ${drop.id}/${rarity}`);
    let mean;
    if (rarity === 'limited') {
      const sw = pool.reduce((a, it) => a + it.maxSupply, 0);
      mean = pool.reduce((a, it) => a + it.value * it.maxSupply, 0) / sw;
    } else {
      mean = pool.reduce((a, it) => a + it.value, 0) / pool.length;
    }
    ev += (w / total) * mean;
  }
  return ev;
}

const q = (s) => (s === null || s === undefined ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const j = (o) => `${q(JSON.stringify(o))}::jsonb`;

export function botId(i) {
  return `00000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`;
}

function main() {
  const items = buildItems();
  const out = [];
  out.push('-- ============================================================================');
  out.push('-- STEAL THE TECH — catalog seed (GENERATED by scripts/gen-catalog.mjs — do not edit)');
  out.push('-- Idempotent: safe to re-run; updates definitions in place.');
  out.push('-- ============================================================================');
  out.push('');

  out.push('insert into game.rarities (id, tier, label, color, steal_penalty, steal_extra_seconds, xp, expected_supply) values');
  out.push(RARITIES.map((r) => `  (${q(r.id)}, ${r.tier}, ${q(r.label)}, ${q(r.color)}, ${r.stealPenalty}, ${r.stealExtra}, ${r.xp}, ${r.expectedSupply})`).join(',\n'));
  out.push('on conflict (id) do update set tier = excluded.tier, label = excluded.label, color = excluded.color, steal_penalty = excluded.steal_penalty, steal_extra_seconds = excluded.steal_extra_seconds, xp = excluded.xp, expected_supply = excluded.expected_supply;');
  out.push('');

  out.push('insert into game.items (id, name, brand, kind, category, rarity, base_value, base_income, max_supply, tradeable, droppable, event_only, color, accent, flavor, sort) values');
  out.push(items.map((it) => `  (${q(it.id)}, ${q(it.name)}, ${q(it.brand)}, ${q(it.kind)}, ${q(it.category)}, ${q(it.rarity)}, ${it.value}, ${it.income}, ${it.maxSupply ?? 'null'}, ${it.tradeable}, ${it.droppable}, ${it.eventOnly}, ${q(it.color)}, ${q(it.accent)}, ${q(it.flavor)}, ${it.sort})`).join(',\n'));
  out.push('on conflict (id) do update set name = excluded.name, brand = excluded.brand, kind = excluded.kind, category = excluded.category, rarity = excluded.rarity, base_value = excluded.base_value, base_income = excluded.base_income, max_supply = excluded.max_supply, tradeable = excluded.tradeable, droppable = excluded.droppable, event_only = excluded.event_only, color = excluded.color, accent = excluded.accent, flavor = excluded.flavor, sort = excluded.sort;');
  out.push('');

  const limited = items.filter((it) => it.maxSupply);
  out.push('insert into game.limited_item_supply (item_id, max_supply) values');
  out.push(limited.map((it) => `  (${q(it.id)}, ${it.maxSupply})`).join(',\n'));
  out.push('on conflict (item_id) do update set max_supply = excluded.max_supply;');
  out.push('');

  out.push('insert into game.market_state (item_id, price, demand) values');
  out.push(items.map((it) => `  (${q(it.id)}, ${it.value}, 50)`).join(',\n'));
  out.push('on conflict (item_id) do nothing;');
  out.push('');

  const evReport = [];
  out.push('insert into game.drop_types (id, name, price, min_level, requires_key, event_only, weights, xp, sort, description) values');
  out.push(DROPS.map((d, i) => {
    const ev = dropEV(d, items);
    const price = nice(ev * d.priceFactor, 2);
    evReport.push({ drop: d.id, expectedValue: Math.round(ev), price, ratio: +(ev / price).toFixed(3) });
    return `  (${q(d.id)}, ${q(d.name)}, ${price}, ${d.minLevel}, ${d.requiresKey}, ${d.eventOnly}, ${j(d.weights)}, ${d.xp}, ${i}, ${q(d.description)})`;
  }).join(',\n'));
  out.push('on conflict (id) do update set name = excluded.name, price = excluded.price, min_level = excluded.min_level, requires_key = excluded.requires_key, event_only = excluded.event_only, weights = excluded.weights, xp = excluded.xp, sort = excluded.sort, description = excluded.description;');
  out.push('');

  const up = [];
  for (const [kind, rows] of Object.entries(UPGRADES)) {
    for (const [level, cost, value, name] of rows) up.push(`  (${q(kind)}, ${level}, ${cost}, ${value}, ${q(name)})`);
  }
  out.push('insert into game.upgrade_levels (kind, level, cost, value, name) values');
  out.push(up.join(',\n'));
  out.push('on conflict (kind, level) do update set cost = excluded.cost, value = excluded.value, name = excluded.name;');
  out.push('');

  out.push('insert into game.quests (id, period, title, metric, target, reward, sort) values');
  out.push(QUESTS.map(([id, period, title, metric, target, reward], i) => `  (${q(id)}, ${q(period)}, ${q(title)}, ${q(metric)}, ${target}, ${j(reward)}, ${i})`).join(',\n'));
  out.push('on conflict (id) do update set period = excluded.period, title = excluded.title, metric = excluded.metric, target = excluded.target, reward = excluded.reward, sort = excluded.sort;');
  out.push('');

  out.push('insert into game.achievements (id, title, description, icon, xp, reward_cash, sort) values');
  out.push(ACHIEVEMENTS.map(([id, title, desc, icon, xp, cash], i) => `  (${q(id)}, ${q(title)}, ${q(desc)}, ${q(icon)}, ${xp}, ${cash}, ${i})`).join(',\n'));
  out.push('on conflict (id) do update set title = excluded.title, description = excluded.description, icon = excluded.icon, xp = excluded.xp, reward_cash = excluded.reward_cash, sort = excluded.sort;');
  out.push('');

  out.push('insert into game.cosmetics (id, slot, name, price, unlock, data, sort) values');
  out.push(COSMETICS.map(([id, slot, name, price, unlock, data], i) => `  (${q(id)}, ${q(slot)}, ${q(name)}, ${price}, ${q(unlock)}, ${j(data)}, ${i})`).join(',\n'));
  out.push('on conflict (id) do update set slot = excluded.slot, name = excluded.name, price = excluded.price, unlock = excluded.unlock, data = excluded.data, sort = excluded.sort;');
  out.push('');

  out.push('insert into game.event_types (id, title, icon, description, category, price_mult, demand_boost, income_mult, luck_mult, weight) values');
  out.push(EVENT_TYPES.map(([id, title, icon, desc, cat, pm, db, im, lm, w]) => `  (${q(id)}, ${q(title)}, ${q(icon)}, ${q(desc)}, ${q(cat)}, ${pm}, ${db}, ${im}, ${lm}, ${w})`).join(',\n'));
  out.push('on conflict (id) do update set title = excluded.title, icon = excluded.icon, description = excluded.description, category = excluded.category, price_mult = excluded.price_mult, demand_boost = excluded.demand_boost, income_mult = excluded.income_mult, luck_mult = excluded.luck_mult, weight = excluded.weight;');
  out.push('');

  out.push('insert into game.level_titles (level, title) values');
  out.push(LEVEL_TITLES.map(([l, t]) => `  (${l}, ${q(t)})`).join(',\n'));
  out.push('on conflict (level) do update set title = excluded.title;');
  out.push('');

  out.push('-- NPC players. Their starting collections are rolled on the first world tick.');
  out.push('insert into game.profiles (id, username, is_bot, bot, cash, level, xp) values');
  out.push(BOTS.map((b, i) => {
    const level = { rookie: 2, collector: 12, raider: 14, trader: 16, whale: 30 }[b.style] + b.base * 2;
    const bot = { style: b.style, plan: b.plan, defend: b.defend, extra: b.extra || [], tutorial: !!b.tutorial, bio: b.bio, seeded: false };
    return `  (${q(botId(i))}, ${q(b.name)}, true, ${j(bot)}, ${b.cash}, ${level}, 0)`;
  }).join(',\n'));
  out.push('on conflict (id) do update set bot = game.profiles.bot || jsonb_build_object(\'style\', excluded.bot->\'style\', \'plan\', excluded.bot->\'plan\', \'defend\', excluded.bot->\'defend\', \'extra\', excluded.bot->\'extra\', \'tutorial\', excluded.bot->\'tutorial\', \'bio\', excluded.bot->\'bio\');');
  out.push('');
  out.push('insert into game.bases (player_id, base_level, security_level, vault_level) values');
  out.push(BOTS.map((b, i) => `  (${q(botId(i))}, ${b.base}, ${b.security}, ${b.vault})`).join(',\n'));
  out.push('on conflict (player_id) do nothing;');
  out.push('');
  out.push('insert into game.player_stats (player_id) values');
  out.push(BOTS.map((b, i) => `  (${q(botId(i))})`).join(',\n'));
  out.push('on conflict (player_id) do nothing;');
  out.push('');

  writeFileSync(OUT, out.join('\n'));

  // Report
  const byR = {};
  for (const it of items) byR[it.rarity] = (byR[it.rarity] || 0) + 1;
  console.log(`catalog: ${items.length} items`, byR);
  console.table(evReport);
  const tvs = items.filter((it) => it.kind === 'tv' && (it.droppable || it.eventOnly));
  console.log(`droppable TVs: ${tvs.length}`);
  console.log(`wrote ${OUT}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
