/* Packs engine.js + pilot.src.js into a self-contained bookmarklet and writes
   install.html and sbc-autopilot.user.js.
   Run: node fc26/build.mjs      (no dependencies) */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const read = f => fs.readFileSync(path.join(dir, f), 'utf8');

/* Conservative squeeze: drop whole-line comments and indentation only. Anything
   cleverer risks mangling a regex or a string, and the payload has to keep working
   with no build-time test of its own beyond `node --check`. */
function squeeze(src) {
  const out = [];
  let inBlock = false;
  for (const raw of src.split('\n')) {
    let line = raw.trim();
    if (inBlock) { if (line.includes('*/')) { inBlock = false; line = line.slice(line.indexOf('*/') + 2).trim(); } else continue; }
    if (!line) continue;
    if (line.startsWith('//')) continue;
    while (line.startsWith('/*')) {
      const end = line.indexOf('*/');
      if (end === -1) { inBlock = true; line = ''; break; }
      line = line.slice(end + 2).trim();
    }
    if (!line) continue;
    out.push(line);
  }
  return out.join('\n');
}

const engine = read('engine.js');
const pilot = read('pilot.src.js');
const payload = squeeze(engine) + '\n' + squeeze(pilot);
const bookmarklet = 'javascript:' + encodeURIComponent('(function(){' + payload + '})();');

const kb = n => (n / 1024).toFixed(1) + ' KB';
console.log(`engine ${kb(engine.length)} + pilot ${kb(pilot.length)} → payload ${kb(payload.length)} → bookmarklet ${kb(bookmarklet.length)}`);
if (bookmarklet.length > 100000) console.warn('WARNING: bookmarklet is large; some browsers may refuse to store it.');

/* userscript — the sturdier install for anyone running Tampermonkey */
const userscript = `// ==UserScript==
// @name         SBC Autopilot
// @namespace    https://github.com/jackrkingsbury-byte/Escape
// @version      1.0.0
// @description  Reads your club and the SBC on screen in the FUT Web App and works out the cheapest squad that passes. Read-only: it never clicks, submits or uploads anything.
// @match        https://www.ea.com/*ultimate-team/web-app/*
// @match        https://www.ea.com/*fifa/ultimate-team/web-app/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==
/* Unofficial fan-made tool. Not affiliated with, endorsed by, or connected to EA Sports.
   Generated by fc26/build.mjs — edit fc26/engine.js or fc26/pilot.src.js instead. */
(function(){
${payload}
})();
`;
fs.writeFileSync(path.join(dir, 'sbc-autopilot.user.js'), userscript);

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const install = read('install.template.html')
  .replace('__BOOKMARKLET_HREF__', esc(bookmarklet))
  .replace('__BOOKMARKLET_JSON__', JSON.stringify(bookmarklet).replace(/</g, '\\u003c'))
  .replace('__SIZE__', kb(bookmarklet.length));
fs.writeFileSync(path.join(dir, 'install.html'), install);
console.log('wrote install.html and sbc-autopilot.user.js');
