// ==UserScript==
// @name         SBC Autopilot
// @namespace    https://github.com/jackrkingsbury-byte/Escape
// @version      1.0.0
// @description  Reads your club and the SBC on screen in the FUT Web App and works out the cheapest squad that passes. Read-only: it never clicks, submits or uploads anything.
// @match        https://www.ea.com/*ultimate-team/web-app/*
// @match        https://www.ea.com/*fifa/ultimate-team/web-app/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==
/* Unofficial fan-made tool. Not affiliated with, endorsed by, or connected to EA Sports.
   Generated by fc26/build.mjs — edit fc26/engine.js or fc26/pilot.src.js instead. */
(function(){
(function(root){
"use strict";
const norm=s=>String(s||'').toLowerCase().replace(/[._''`-]/g,' ').replace(/\s+/g,' ').trim();
const titled=s=>String(s||'').trim();
function coins(n){
n=Math.round(n||0);
if(n===0)return '0';
if(n>=1e6)return (n/1e6).toFixed(n>=1e7?1:2).replace(/\.?0+$/,'')+'M';
if(n>=1e4)return Math.round(n/1e3)+'K';
return n.toLocaleString('en-US');
}
function parsePrice(tok){
const m=String(tok).replace(/[, ]/g,'').match(/^([\d.]+)\s*([km])?$/i);
if(!m)return null;
let v=parseFloat(m[1]); if(!isFinite(v))return null;
const u=(m[2]||'').toLowerCase();
if(u==='k')v*=1e3; else if(u==='m')v*=1e6;
return Math.round(v);
}
const POSITIONS=['GK','RB','RWB','CB','LB','LWB','CDM','CM','CAM','RM','LM','RW','LW','CF','ST'];
const POS_SET=new Set(POSITIONS);
const RELATED={
GK:['GK'],
CB:['CB'],
RB:['RB','RWB'], RWB:['RWB','RB'],
LB:['LB','LWB'], LWB:['LWB','LB'],
CDM:['CDM','CM'], CM:['CM','CDM','CAM'], CAM:['CAM','CM','CF'],
RM:['RM','RW'], RW:['RW','RM'],
LM:['LM','LW'], LW:['LW','LM'],
CF:['CF','ST','CAM'], ST:['ST','CF']
};
const FORMATIONS=[
{name:'4-4-2',      rows:[['GK'],['LB','CB','CB','RB'],['LM','CM','CM','RM'],['ST','ST']]},
{name:'4-3-3',      rows:[['GK'],['LB','CB','CB','RB'],['CM','CM','CM'],['LW','ST','RW']]},
{name:'4-2-3-1',    rows:[['GK'],['LB','CB','CB','RB'],['CDM','CDM'],['LM','CAM','RM'],['ST']]},
{name:'4-1-2-1-2',  rows:[['GK'],['LB','CB','CB','RB'],['CDM'],['CM','CM'],['CAM'],['ST','ST']]},
{name:'4-3-2-1',    rows:[['GK'],['LB','CB','CB','RB'],['CM','CM','CM'],['CF','CF'],['ST']]},
{name:'3-5-2',      rows:[['GK'],['CB','CB','CB'],['LM','CM','CM','CM','RM'],['ST','ST']]},
{name:'5-3-2',      rows:[['GK'],['LWB','CB','CB','CB','RWB'],['CM','CM','CM'],['ST','ST']]},
{name:'4-4-1-1',    rows:[['GK'],['LB','CB','CB','RB'],['LM','CM','CM','RM'],['CF'],['ST']]},
{name:'4-2-2-2',    rows:[['GK'],['LB','CB','CB','RB'],['CDM','CDM'],['CAM','CAM'],['ST','ST']]},
{name:'3-4-3',      rows:[['GK'],['CB','CB','CB'],['LM','CM','CM','RM'],['LW','ST','RW']]}
];
const NATIONS=['england','france','spain','germany','italy','portugal','brazil','argentina','netherlands','belgium','croatia','uruguay','colombia','norway','sweden','denmark','poland','morocco','senegal','nigeria','ghana','ivory coast','cameroon','egypt','algeria','japan','south korea','australia','united states','usa','canada','mexico','chile','ecuador','peru','paraguay','serbia','switzerland','austria','scotland','wales','ireland','republic of ireland','northern ireland','turkey','greece','ukraine','russia','czech republic','czechia','slovakia','slovenia','hungary','romania','bulgaria','finland','iceland','albania','bosnia and herzegovina','north macedonia','montenegro','georgia','armenia','israel','iran','iraq','saudi arabia','qatar','united arab emirates','tunisia','mali','burkina faso','guinea','gabon','congo','dr congo','zambia','south africa','jamaica','costa rica','honduras','panama','venezuela','bolivia','china pr','china','new zealand','kosovo','luxembourg','cyprus','moldova','belarus','lithuania','latvia','estonia','uzbekistan'];
const NATION_SET=new Set(NATIONS);
const LEAGUE_ALIASES={
'premier league':'Premier League','epl':'Premier League','english premier league':'Premier League','pl':'Premier League',
'laliga':'LALIGA','la liga':'LALIGA','laliga ea sports':'LALIGA','spanish la liga':'LALIGA','laliga santander':'LALIGA',
'serie a':'Serie A','italian serie a':'Serie A','serie a tim':'Serie A',
'bundesliga':'Bundesliga','german bundesliga':'Bundesliga','1 bundesliga':'Bundesliga',
'ligue 1':'Ligue 1','french ligue 1':'Ligue 1','ligue 1 uber eats':'Ligue 1',
'eredivisie':'Eredivisie','dutch eredivisie':'Eredivisie',
'liga portugal':'Liga Portugal','primeira liga':'Liga Portugal','portuguese liga':'Liga Portugal',
'mls':'MLS','major league soccer':'MLS',
'saudi pro league':'Saudi Pro League','roshn saudi league':'Saudi Pro League',
'efl championship':'EFL Championship','championship':'EFL Championship',
'liga mx':'Liga MX','turkish super lig':'Süper Lig','super lig':'Süper Lig','süper lig':'Süper Lig',
'scottish premiership':'Scottish Premiership','belgian pro league':'Belgian Pro League',
'liga profesional de futbol':'Liga Profesional','brasileirao':'Brasileirão','brasileirão':'Brasileirão','serie a brazil':'Brasileirão',
'austrian bundesliga':'Austrian Bundesliga','swiss super league':'Swiss Super League',
'danish superliga':'Superliga','allsvenskan':'Allsvenskan','eliteserien':'Eliteserien',
'k league 1':'K League 1','j1 league':'J1 League','a league':'A-League','a-league':'A-League',
'women s super league':"Women's Super League",'wsl':"Women's Super League",
'icons':'Icons','icon':'Icons','heroes':'Heroes','hero':'Heroes'
};
let reqId=0;   // only id generation is shared state
const HEADER_MAP={
name:['name','player','playername','player name'],
rating:['rating','ovr','overall','rat','score'],
pos:['pos','position','positions','pref pos','preferred position'],
nation:['nation','nationality','country'],
league:['league','comp','competition'],
club:['club','team'],
price:['price','value','cost','coins','buy now','bin'],
tags:['tags','tag','notes','type','quality']
};
function headerKind(cell){
const n=norm(cell);
for(const k in HEADER_MAP) if(HEADER_MAP[k].includes(n)) return k;
return null;
}
function splitFields(line){
if(line.includes('\t')) return line.split('\t');
if(line.includes('|'))  return line.split('|');
if(line.includes(';'))  return line.split(';');
const byComma=line.includes(',')?line.split(','):[line];
const bySpace=line.split(/\s{2,}/);
return bySpace.filter(s=>s.trim()).length>byComma.filter(s=>s.trim()).length?bySpace:byComma;
}
function posTokens(cell){
const parts=String(cell).split(/[\/,\s]+/).map(p=>p.trim().toUpperCase()).filter(Boolean);
if(!parts.length) return null;
return parts.every(p=>POS_SET.has(p)) ? [...new Set(parts)] : null;
}
const TAGWORDS={
untradeable:['untradeable','untradable','ut','unt','u','loan','loaned'],
rare:['rare','r'],
special:['totw','if','sif','mif','special','tots','toty','promo','inform'],
icon:['icon','icons'],
hero:['hero','heroes','fut hero']
};
function tagKind(tok){
const n=norm(tok);
for(const k in TAGWORDS) if(TAGWORDS[k].includes(n)) return k;
return null;
}
function leagueCanon(cell){
const n=norm(cell);
if(LEAGUE_ALIASES[n]) return LEAGUE_ALIASES[n];
return null;
}
function parseClub(text){
const out=[],bad=[];
const lines=String(text||'').split(/\r?\n/).map(l=>l.trim()).filter(l=>l && !/^[-=_#*]+$/.test(l));
if(!lines.length) return {players:[],bad:[]};
let map=null, start=0;
const h=splitFields(lines[0]).map(c=>c.trim());
const kinds=h.map(headerKind);
if(kinds.filter(Boolean).length>=3){
map={}; kinds.forEach((k,i)=>{ if(k&&map[k]===undefined) map[k]=i; });
start=1;
}
for(let li=start;li<lines.length;li++){
const raw=lines[li];
const cells=splitFields(raw).map(c=>c.trim());
if(!cells.some(Boolean)){bad.push(raw);continue;}
const p={name:'',rating:0,pos:[],nation:'',league:'',club:'',price:0,untradeable:false,rare:false,special:false,icon:false,hero:false};
if(map){
const g=k=>map[k]!==undefined?String(cells[map[k]]||'').trim():'';
p.name=g('name');
p.rating=parseInt(g('rating'),10)||0;
p.pos=posTokens(g('pos'))||[];
p.nation=titled(g('nation'));
p.league=leagueCanon(g('league'))||titled(g('league'));
p.club=titled(g('club'));
const pr=parsePrice(g('price')); p.price=pr===null?0:pr;
const tagcell=(g('tags')+' '+g('price')).split(/[\s,\/]+/);
tagcell.forEach(t=>{const k=tagKind(t); if(k){ if(k==='untradeable')p.untradeable=true; else p[k]=true; }});
} else {
const left=[];
cells.forEach(cell=>{
const c=cell.trim(); if(!c) return;
const k=tagKind(c);
if(k){ if(k==='untradeable')p.untradeable=true; else p[k]=true; return; }
if(!p.rating){
const r=parseInt(c,10);
if(String(r)===c.replace(/^0+(?=\d)/,'') && r>=40 && r<=99){ p.rating=r; return; }
}
const pt=posTokens(c);
if(pt && !p.pos.length){ p.pos=pt; return; }
const lg=leagueCanon(c);
if(lg && !p.league){ p.league=lg; return; }
if(NATION_SET.has(norm(c)) && !p.nation){ p.nation=titled(c); return; }
const pr=parsePrice(c);
if(pr!==null && !p._pricedone){ p.price=pr; p._pricedone=true; return; }
left.push(c);
});
if(left.length){ p.name=left.shift(); }
left.forEach(v=>{
if(!p.nation && NATION_SET.has(norm(v))) p.nation=titled(v);
else if(!p.club) p.club=titled(v);
else if(!p.league) p.league=titled(v);
else if(!p.nation) p.nation=titled(v);
});
}
delete p._pricedone;
if(!p.name || !p.rating){ bad.push(raw); continue; }
if(!p.pos.length) p.pos=['CM'];
if(p.icon||p.hero) p.rare=true;
if(p.special) p.rare=true; // specials count as rare for SBC purposes
p.id=out.length;
p.key=norm(p.name)+'|'+p.rating;
out.push(p);
}
return {players:out,bad};
}
function quality(r){ return r>=75?'gold':(r>=65?'silver':'bronze'); }
const KIND_LABEL={
rating:'Squad rating', chem:'Team chemistry', size:'Players in squad',
sameClub:'Same club count', sameLeague:'Same league count', sameNation:'Same nation count',
distinctClubs:'Different clubs', distinctLeagues:'Different leagues', distinctNations:'Different nations',
rare:'Rare players', special:'Special / TOTW players', quality:'Players of quality', ovr:'Players rated OVR+',
namedLeague:'Players from league', namedNation:'Players from nation', namedClub:'Players from club'
};
const NEEDS_PARAM={quality:1,ovr:1,namedLeague:1,namedNation:1,namedClub:1};
function newReq(kind,op,value,param,auto){
return {id:++reqId,kind,op:op||'min',value:Number(value)||0,param:param||'',auto:!!auto};
}
function opFrom(text){
const t=norm(text);
if(/\bmax(imum)?\b|\bno more than\b|\bup to\b/.test(t)) return 'max';
if(/\bexact(ly)?\b/.test(t)) return 'exactly';
return 'min';
}
function lexicon(club){
const L=new Map(),N=new Map(),C=new Map();
club.forEach(p=>{
if(p.league) L.set(norm(p.league),p.league);
if(p.nation) N.set(norm(p.nation),p.nation);
if(p.club)   C.set(norm(p.club),p.club);
});
Object.entries(LEAGUE_ALIASES).forEach(([k,v])=>{ if(!L.has(k)) L.set(k,v); });
NATIONS.forEach(n=>{ if(!N.has(n)) N.set(n,n.replace(/\b\w/g,c=>c.toUpperCase())); });
return {L,N,C};
}
function findNamed(line,club){
const n=norm(line), lex=lexicon(club);
let best=null;
const scan=(map,kind)=>{
for(const [k,v] of map){
if(k.length<3) continue;
if(n.includes(k) && (!best||k.length>best.key.length)) best={kind,key:k,value:v};
}
};
scan(lex.L,'namedLeague'); scan(lex.N,'namedNation'); scan(lex.C,'namedClub');
return best;
}
function numbersIn(line){
const m=String(line).match(/\d+/g);
return m?m.map(Number):[];
}
function parseSbc(text,club){
const found=[],unparsed=[];
const lines=String(text||'').split(/\r?\n/).map(l=>l.trim()).filter(Boolean);
for(const raw of lines){
const chunks=raw.split(/\s*[•·;]\s*|\s{3,}(?=[A-Z])/).map(c=>c.trim()).filter(Boolean);
let anyChunk=false;
for(const line of chunks){
const r=parseReqLine(line,club);
if(r){ found.push(...r); anyChunk=true; }
else if(/\d/.test(line) && line.length>3) unparsed.push(line);
}
if(!anyChunk && !/\d/.test(raw) && raw.length>3){ /* headings — ignore silently */ }
}
const seen=new Map();
found.forEach(r=>seen.set(r.kind+'|'+norm(r.param)+'|'+r.op,r));
return {reqs:[...seen.values()],unparsed};
}
function parseReqLine(line,club){
const t=norm(line);
if(!/\d/.test(t) && !/\b(gold|silver|bronze)\b/.test(t)) return null;
const nums=numbersIn(t);
const op=opFrom(t);
const first=nums.length?nums[nums.length-1]:0; // EA puts the number last: "Squad Rating: Min. 84"
if(/\b(squad|team)\s*(overall|rating|ovr)\b|\brating\s*(of the squad)?\b/.test(t) && !/chem/.test(t)){
const v=nums.find(n=>n>=40&&n<=99);
if(v) return [newReq('rating',op,v,'',true)];
}
if(/chem/.test(t)){
const v=nums.find(n=>n>=0&&n<=33) ?? first;
return [newReq('chem',op,v,'',true)];
}
if(/(number of players|players in (the )?squad|squad size|# of players)/.test(t)){
const v=nums.find(n=>n>=1&&n<=11)||11;
return [newReq('size','exactly',v,'',true)];
}
if(/same\s+club/.test(t))   return [newReq('sameClub',op,first,'',true)];
if(/same\s+league/.test(t)) return [newReq('sameLeague',op,first,'',true)];
if(/same\s+(nation|country)/.test(t)) return [newReq('sameNation',op,first,'',true)];
if(/^(number of\s+)?(different\s+|unique\s+)?clubs?\b/.test(t)&&!/players/.test(t))   return [newReq('distinctClubs',op,first,'',true)];
if(/^(number of\s+)?(different\s+|unique\s+)?leagues?\b/.test(t)&&!/players/.test(t)) return [newReq('distinctLeagues',op,first,'',true)];
if(/^(number of\s+)?(different\s+|unique\s+)?(nations?|nationalities|countries)\b/.test(t)&&!/players/.test(t)) return [newReq('distinctNations',op,first,'',true)];
const ovrM=t.match(/(\d{2})\s*\+?\s*(ovr|rated|rating|overall)/)||t.match(/(ovr|rated|rating|overall)\s*(\d{2})\s*\+/);
if(ovrM){
const bucket=Number(ovrM[1].match(/\d+/)?ovrM[1]:ovrM[2]);
const rest=nums.filter(n=>n!==bucket);
const cnt=rest.length?rest[rest.length-1]:1;
if(bucket>=40&&bucket<=99) return [newReq('ovr',op,cnt,String(bucket),true)];
}
if(/quality/.test(t)||/\b(gold|silver|bronze)\b/.test(t)){
const q=(t.match(/\b(gold|silver|bronze)\b/)||[])[1];
if(q){
const cnt=nums.find(n=>n>=1&&n<=11)||11;
return [newReq('quality',op==='max'?'max':'min',cnt,q,true)];
}
}
if(/\brare\b/.test(t))  return [newReq('rare',op,first||1,'',true)];
if(/\b(totw|team of the week|inform|in ?form|special)\b/.test(t)) return [newReq('special',op,first||1,'',true)];
const named=findNamed(line,club);
if(named){
const cnt=nums.find(n=>n>=1&&n<=11)||1;
return [newReq(named.kind,op,cnt,named.value,true)];
}
if(/^(nationality|nations?)\b/.test(t)) return [newReq('sameNation',op,first,'',true)];
if(/^leagues?\b/.test(t)) return [newReq('sameLeague',op,first,'',true)];
if(/^clubs?\b/.test(t))   return [newReq('sameClub',op,first,'',true)];
return null;
}
function squadRating(ratings){
const n=ratings.length||1;
let sum=0; for(const r of ratings) sum+=r;
const avg=sum/n;
let excess=0; for(const r of ratings) if(r>avg) excess+=r-avg;
const exact=(sum+excess)/n;
return {exact,rating:Math.floor(exact+1e-9)};
}
const CLUB_T=[[7,3],[4,2],[2,1]], LEAGUE_T=[[8,3],[5,2],[3,1]], NATION_T=[[8,3],[5,2],[2,1]];
function tier(count,table){ for(const [need,pts] of table) if(count>=need) return pts; return 0; }
function prepareEligibility(players,formation,relPos){
const slots=formation.rows.flat();
const key=formation.name+'|'+(relPos?'rel':'strict');
for(const p of players){
if(p._eligKey===key) continue;
const allowed=new Set();
p.pos.forEach(pp=>{ (relPos?(RELATED[pp]||[pp]):[pp]).forEach(x=>allowed.add(x)); });
p._elig=slots.map(s=>allowed.has(s));
p._eligKey=key;
}
return slots;
}
function assignSlots(players,slots){
const n=players.length, S=slots.length;
const elig=players.map(p=>p._elig);
const demand=new Array(S).fill(0);
for(let s=0;s<S;s++) for(let i=0;i<n;i++) if(elig[i][s]) demand[s]++;
const order=players.map((p,i)=>i).sort((a,b)=>players[b]._pot-players[a]._pot);
const slotTaken=new Array(S).fill(-1);
const assign=new Array(n).fill(-1);
for(const i of order){
let best=-1,bestDemand=1e9;
for(let s=0;s<S;s++){
if(slotTaken[s]!==-1||!elig[i][s]) continue;
if(demand[s]<bestDemand){bestDemand=demand[s];best=s;}
}
if(best>=0){ slotTaken[best]=i; assign[i]=best; }
}
const free=[]; for(let s=0;s<S;s++) if(slotTaken[s]===-1) free.push(s);
for(let i=0;i<n;i++) if(assign[i]===-1){ const s=free.pop(); if(s!==undefined){assign[i]=s;slotTaken[s]=i;} }
const got=(i,s)=> (s>=0&&elig[i][s])?players[i]._pot:0;
for(let pass=0;pass<2;pass++){
let improved=false;
for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){
const si=assign[i],sj=assign[j];
if(si===sj) continue;
const delta=(got(i,sj)+got(j,si))-(got(i,si)+got(j,sj));
if(delta>0){ assign[i]=sj; assign[j]=si; improved=true; }
}
if(!improved) break;
}
return assign;
}
function chemistry(players,formation,relPos){
const slots=prepareEligibility(players,formation,relPos);
const cCount={},lCount={},nCount={};
players.forEach(p=>{
const c=norm(p.club),l=norm(p.league),nt=norm(p.nation);
if(c) cCount[c]=(cCount[c]||0)+1;
if(l) lCount[l]=(lCount[l]||0)+(p.hero?2:1);
if(nt) nCount[nt]=(nCount[nt]||0)+(p.icon?2:1);
});
players.forEach(p=>{
if(p.icon||p.hero){ p._pot=3; return; }
const pts=tier(cCount[norm(p.club)]||0,CLUB_T)+tier(lCount[norm(p.league)]||0,LEAGUE_T)+tier(nCount[norm(p.nation)]||0,NATION_T);
p._pot=Math.min(3,pts);
});
const assign=assignSlots(players,slots);
let total=0; const detail=[];
players.forEach((p,i)=>{
const s=assign[i], slot=s>=0?slots[s]:'—';
const inPos=s>=0&&!!p._elig[s];
const got=inPos?p._pot:0;
total+=got;
detail.push({player:p,slot,slotIndex:s,inPos,chem:got});
});
return {total:Math.min(33,total),detail};
}
function groupMax(players,field){
const m={}; let best=0;
players.forEach(p=>{ const k=norm(p[field]); if(!k)return; m[k]=(m[k]||0)+1; if(m[k]>best)best=m[k]; });
return best;
}
function distinct(players,field){
const s=new Set(); players.forEach(p=>{const k=norm(p[field]); if(k)s.add(k);}); return s.size;
}
function reqActual(r,ctx){
const P=ctx.players;
switch(r.kind){
case 'rating': return ctx.rating.rating;
case 'chem':   return ctx.chem.total;
case 'size':   return P.length;
case 'sameClub':   return groupMax(P,'club');
case 'sameLeague': return groupMax(P,'league');
case 'sameNation': return groupMax(P,'nation');
case 'distinctClubs':   return distinct(P,'club');
case 'distinctLeagues': return distinct(P,'league');
case 'distinctNations': return distinct(P,'nation');
case 'rare':    return P.filter(p=>p.rare).length;
case 'special': return P.filter(p=>p.special).length;
case 'quality': return P.filter(p=>quality(p.rating)===r.param).length;
case 'ovr':     return P.filter(p=>p.rating>=Number(r.param||0)).length;
case 'namedLeague': return P.filter(p=>norm(p.league)===norm(r.param)).length;
case 'namedNation': return P.filter(p=>norm(p.nation)===norm(r.param)).length;
case 'namedClub':   return P.filter(p=>norm(p.club)===norm(r.param)).length;
}
return 0;
}
function reqShortfall(r,actual,ctx){
if(r.op==='min')     return Math.max(0,r.value-actual);
if(r.op==='max')     return Math.max(0,actual-r.value);
return Math.abs(actual-r.value);
}
function reqLabel(r){
const base=KIND_LABEL[r.kind]||r.kind;
const opw=r.op==='min'?'at least':(r.op==='max'?'at most':'exactly');
if(r.kind==='rating'||r.kind==='chem'||r.kind==='size') return `${base} ${opw} ${r.value}`;
if(r.kind==='ovr') return `${opw} ${r.value} player(s) rated ${r.param}+`;
if(r.kind==='quality') return `${opw} ${r.value} ${r.param} player(s)`;
if(NEEDS_PARAM[r.kind]) return `${opw} ${r.value} from ${r.param}`;
if(r.kind.startsWith('distinct')) return `${base}: ${opw} ${r.value}`;
return `${base} ${opw} ${r.value}`;
}
function evaluate(players,formation,opts,reqs){
const rating=squadRating(players.map(p=>p.rating));
const chem=chemistry(players,formation,opts.relPos);
const ctx={players,rating,chem};
let violation=0; const checks=[];
for(const r of reqs){
if(r.kind==='size') continue; // squad size is structural
const actual=reqActual(r,ctx);
let short=reqShortfall(r,actual,ctx);
if(r.kind==='rating'&&r.op==='min'&&opts.safe&&short===0&&rating.exact<r.value+0.5) short=0.5;
const weight=(r.kind==='rating')?1:(r.kind==='chem'?0.35:0.8);
violation+=short*weight;
checks.push({req:r,actual,pass:short===0});
}
return {rating,chem,checks,violation,ctx};
}
function squadCost(players,untradeMul){
let c=0; for(const p of players) c+=p.untradeable?p.price*untradeMul:p.price;
return c;
}
function buildPool(club,formation,opts){
let pool=club.filter(p=>p.rating>0);
if(opts.excludeIcons) pool=pool.filter(p=>!p.icon&&!p.hero);
const CAP=260;
if(pool.length>CAP){
const byCost=[...pool].sort((a,b)=>effCost(a,opts)-effCost(b,opts)).slice(0,CAP-90);
const byRating=[...pool].sort((a,b)=>b.rating-a.rating).slice(0,90);
pool=[...new Set([...byCost,...byRating])];
}
return pool;
}
function effCost(p,opts){ return p.untradeable?p.price*opts.untradeMul:p.price; }
function solveAsync(club,reqs,formation,opts,onProgress,onDone){
const pool=buildPool(club,formation,opts);
const size=(reqs.find(r=>r.kind==='size')||{value:11}).value||11;
if(pool.length<size){ onDone({error:`Only ${pool.length} usable player(s) in your club — need ${size}.`}); return; }
const budget={fast:26000,deep:90000,max:260000}[opts.effort]||90000;
const restarts={fast:6,deep:16,max:34}[opts.effort]||16;
const perRun=Math.max(1200,Math.floor(budget/restarts));
const sortedCost=pool.map(p=>effCost(p,opts)).sort((a,b)=>b-a);
const maxSquadCost=sortedCost.slice(0,size).reduce((a,b)=>a+b,0);
const BIG=Math.max(1e6,(maxSquadCost+1)*4);
let bestValid=null, bestAny=null, run=0;
const gk=pool.filter(p=>p.pos.includes('GK'));
const outfield=pool.filter(p=>!p.pos.includes('GK'));
const needsGK=formation.rows.flat().includes('GK');
function seed(){
const picked=[];
const usedIds=new Set();
if(needsGK&&gk.length){
const g=gk[Math.floor(Math.random()*Math.min(gk.length,6))]||gk[0];
picked.push(g); usedIds.add(g.id);
}
const wantRating=reqs.some(r=>r.kind==='rating'&&r.op==='min');
const candidates=(needsGK?outfield:pool).filter(p=>!usedIds.has(p.id));
const sorted=[...candidates].sort((a,b)=> wantRating ? (b.rating-a.rating)||(effCost(a,opts)-effCost(b,opts)) : (effCost(a,opts)-effCost(b,opts))||(b.rating-a.rating));
const window=wantRating?Math.max(size+6,18):Math.max(size*3,26);
while(picked.length<size&&sorted.length){
const w=Math.min(window,sorted.length);
const i=Math.floor(Math.random()*w);
const p=sorted[i];
if(!usedIds.has(p.id)){picked.push(p);usedIds.add(p.id);}
sorted.splice(i,1);
}
return picked.length===size?picked:null;
}
function score(sq){
const ev=evaluate(sq,formation,opts,reqs);
const cost=squadCost(sq,opts.untradeMul);
return {ev,cost,total:ev.violation*BIG+cost};
}
function propose(sq){
const i=Math.floor(Math.random()*size);
const outP=sq[i];
const isOnlyGK=needsGK&&outP.pos.includes('GK')&&sq.filter(p=>p.pos.includes('GK')).length<2;
const src=isOnlyGK?(gk.length?gk:pool):pool;
const inP=src[Math.floor(Math.random()*src.length)];
if(!inP||sq.some(p=>p.id===inP.id)) return null;
const trial=sq.slice(); trial[i]=inP;
return trial;
}
function record(sq,sc){
if(sc.ev.violation===0){
if(!bestValid||sc.cost<bestValid.cost) bestValid={squad:sq.slice(),ev:sc.ev,cost:sc.cost};
} else if(!bestAny||sc.total<bestAny.total){
bestAny={squad:sq.slice(),ev:sc.ev,cost:sc.cost,total:sc.total,__partial:true};
}
}
function runOne(){
let sq=seed(); if(!sq) return;
let cur=score(sq); record(sq,cur);
const repair=Math.floor(perRun*0.45);
for(let it=0;it<repair;it++){
const trial=propose(sq); if(!trial) continue;
const sc=score(trial);
const delta=sc.total-cur.total;
const T=BIG*0.5*(1-it/repair)+1;
if(delta<0||Math.random()<Math.exp(-delta/T)){ sq=trial; cur=sc; record(sq,cur); }
}
const trim=perRun-repair;
const scale=Math.max(1,maxSquadCost*0.12);
for(let it=0;it<trim;it++){
const trial=propose(sq); if(!trial) continue;
const sc=score(trial);
if(cur.ev.violation===0&&sc.ev.violation>0) continue; // never give up a legal squad
const delta=sc.total-cur.total;
const T=scale*(1-it/trim)+1;
if(delta<0||Math.random()<Math.exp(-delta/T)){ sq=trial; cur=sc; record(sq,cur); }
}
}
function step(){
const chunk=Math.max(1,Math.round(restarts/8));
for(let k=0;k<chunk&&run<restarts;k++,run++) runOne();
onProgress(run/restarts,bestValid);
if(run<restarts) setTimeout(step,0);
else {
const out=bestValid||bestAny;
onDone(out?{best:out}:{error:'No squad found. Loosen a rule or add players.'});
}
}
setTimeout(step,0);
}
root.SBCEngine={
POSITIONS,POS_SET,RELATED,FORMATIONS,NATIONS,NATION_SET,LEAGUE_ALIASES,KIND_LABEL,NEEDS_PARAM,
norm,titled,coins,parsePrice,quality,posTokens,leagueCanon,tagKind,
parseClub,parseSbc,parseReqLine,newReq,findNamed,
squadRating,chemistry,prepareEligibility,assignSlots,
evaluate,reqActual,reqShortfall,reqLabel,squadCost,effCost,buildPool,solveAsync
};
})(typeof window!=='undefined'?window:globalThis);
(function(){
"use strict";
var E=window.SBCEngine;
if(!E){ alert('SBC Autopilot: engine missing — reinstall the bookmarklet.'); return; }
if(window.__SBC_PILOT__){ window.__SBC_PILOT__.toggle(); return; }
var VALUE={74:180,75:420,76:520,77:650,78:820,79:1100,80:1500,81:2100,82:3200,83:5200,84:11000,85:24000,86:44000,87:80000,88:140000,89:250000,90:440000,91:780000};
function estValue(p){
var r=p.rating,v;
if(r<=74) v=Math.max(50,180-(74-r)*12);
else if(r>=91) v=780000*Math.pow(1.75,r-91);
else v=VALUE[r]||1000;
if(p.icon||p.hero) v*=3;
else if(p.special) v*=1.6;
return Math.round(v);
}
var POS_SET=E.POS_SET, NATION_SET=E.NATION_SET, norm=E.norm;
function isRating(t){ return /^\d{2}$/.test(t) && +t>=40 && +t<=99; }
function textBits(el){
var out=[],w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),n;
while(n=w.nextNode()){ var t=(n.nodeValue||'').trim(); if(t) out.push(t); }
return out;
}
function hasPosition(el){
var bits=textBits(el);
for(var i=0;i<bits.length;i++) if(E.posTokens(bits[i])) return true;
return false;
}
function idFromUrl(u){
var clean=String(u).replace(/[?#].*$/,'');
var m=clean.match(/(\d+)[^\/\d]*$/);
return m?m[1]:null;
}
function classifyUrl(u){
var s=String(u).toLowerCase();
if(/league|competition/.test(s)) return 'league';       // checked first: "league" URLs often also say "club"
if(/flag|nation|country/.test(s)) return 'nation';
if(/club|crest|badge|team/.test(s)) return 'club';
return null;
}
function imgUrl(im){
var cands=[im.getAttribute('data-src'),im.getAttribute('data-original'),im.currentSrc,im.getAttribute('src'),im.src];
var first='';
for(var i=0;i<cands.length;i++){
var u=cands[i];
if(!u||/^data:/i.test(u)) continue;
if(!first) first=u;
if(classifyUrl(u)) return u;
}
return first;
}
function imagesIn(tile){
var out=[];
var imgs=tile.querySelectorAll('img');
for(var i=0;i<imgs.length;i++){
out.push({url:imgUrl(imgs[i]),label:imgs[i].alt||imgs[i].title||imgs[i].getAttribute('aria-label')||''});
}
var all=tile.querySelectorAll('*');
if(all.length<=60){ // background-image lookups are expensive; skip on huge subtrees
for(var j=0;j<all.length;j++){
var bg='';
try{ bg=getComputedStyle(all[j]).backgroundImage||''; }catch(e){}
var m=bg.match(/url\(["']?(.*?)["']?\)/);
if(m&&m[1]&&m[1]!=='none') out.push({url:m[1],label:all[j].getAttribute('aria-label')||all[j].title||''});
}
}
return out;
}
function readTile(tile,ratingNode){
var p={name:'',rating:+ratingNode.nodeValue.trim(),pos:[],nation:'',league:'',club:'',
price:0,untradeable:false,rare:false,special:false,icon:false,hero:false};
var bits=textBits(tile),seenPos={},nameCands=[];
for(var i=0;i<bits.length;i++){
var t=bits[i],pt=E.posTokens(t);
if(pt){ for(var q=0;q<pt.length;q++) if(!seenPos[pt[q]]){seenPos[pt[q]]=1;p.pos.push(pt[q]);} continue; }
if(/^\d+$/.test(t)) continue;
if(t.length>1 && /[a-zA-ZÀ-ɏ]/.test(t)) nameCands.push(t);
}
function nameScore(t){
var s=t.length;
if(/[·•|]/.test(t)) s-=40;
if(/\b(rare|common|gold|silver|bronze|loan|loans|untradeable|tradeable|contract|fitness|chemistry|quality|totw|special|position|squad|pack)\b/i.test(t)) s-=40;
if(/\d/.test(t)) s-=3;
return s;
}
var imgs=imagesIn(tile);
for(var k=0;k<imgs.length;k++){
var im=imgs[k], lab=im.label.trim(), kind=classifyUrl(im.url), id=idFromUrl(im.url);
if(lab){
if(!p.nation && NATION_SET.has(norm(lab))){ p.nation=lab; continue; }
var lg=E.leagueCanon(lab);
if(lg && !p.league){ p.league=lg; continue; }
}
if(!kind||!id) continue;
if(kind==='club'  && !p.club)   p.club='club#'+id;
if(kind==='league'&& !p.league) p.league='league#'+id;
if(kind==='nation'&& !p.nation) p.nation='nation#'+id;
}
var cls=((tile.className&&tile.className.baseVal!==undefined?tile.className.baseVal:tile.className)||'')+' '+(tile.getAttribute('data-type')||'');
var c=cls.toLowerCase(), joined=bits.join(' ').toLowerCase();
if(/\bicon/.test(c)) p.icon=true;
if(/\bhero/.test(c)) p.hero=true;
if(/rare|special|totw|inform|informs/.test(c)||/\brare\b/.test(joined)) p.rare=true;
if(/totw|team of the week|inform/.test(c)||/\btotw\b|team of the week/.test(joined)) p.special=true;
if(/untradeable|untradable/.test(joined)) p.untradeable=true;
if(p.icon||p.hero||p.special) p.rare=true;
nameCands.sort(function(a,b){ return nameScore(b)-nameScore(a); });
p.name=nameCands[0]||('Player '+p.rating);
if(!p.pos.length) return null;
if(p.rating<40||p.rating>99) return null;
p.price=estValue(p);
p.key=norm(p.name)+'|'+p.rating+'|'+p.club+'|'+p.nation;
return p;
}
function findTile(ratingNode){
var el=ratingNode.parentElement, fallback=null;
for(var up=0; up<7 && el && el!==document.body; up++, el=el.parentElement){
if(el.querySelectorAll('*').length>60) break;
if(!hasPosition(el)) continue;
if(!fallback) fallback=el;
if(el.querySelector('img')) return el;
}
return fallback;
}
function ratingNodesIn(el){
var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),n,c=0;
while(n=w.nextNode()){ if(isRating((n.nodeValue||'').trim())) c++; }
return c;
}
function harvestOnce(store){
var w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),n,added=0,seen=0;
var ratingNodes=[];
while(n=w.nextNode()){ var t=(n.nodeValue||'').trim(); if(isRating(t)) ratingNodes.push(n); }
for(var i=0;i<ratingNodes.length;i++){
var rn=ratingNodes[i], tile=findTile(rn);
if(!tile) continue;
if(ratingNodesIn(tile)>3) continue;   // several ratings inside means we grabbed a list
seen++;
var p=readTile(tile,rn);
if(!p) continue;
if(store.byKey[p.key]) continue;   // identical duplicate cards collapse — see README
store.byKey[p.key]=p;
p.id=store.list.length;
store.list.push(p);
added++;
}
return {added:added,tiles:seen};
}
var REQ_HINT=/rating|chem|league|nation|club|rare|quality|players|squad|ovr|totw|gold|silver|bronze|country/i;
var REQ_SHAPE=/(\bmin\b|\bmax\b|\bexact|:|\d\s*$)/i;   // "label: value", or a min/max/exactly
var TILE_SHAPE=/\d{2}\s*(GK|CB|LB|RB|LWB|RWB|CDM|CM|CAM|LM|RM|LW|RW|CF|ST)\b/i;
var REQ_NOISE=/\b(reward|rewards|pack|packs|coins|formation|expires|expiry|repeatable|refresh|remaining|complete[ds]?|submit|challenge[sd]?|untradeable pack)\b/i;
function looksLikeRequirement(t){
if(!t||t.length<5||t.length>110) return false;
if(REQ_NOISE.test(t)) return false;
if(!REQ_HINT.test(t)) return false;
if(!/\d/.test(t) && !/\b(gold|silver|bronze)\b/i.test(t)) return false;
if(!REQ_SHAPE.test(t)) return false;
if(TILE_SHAPE.test(t)) return false;                 // that's a player card, not a rule
var bits=t.split(/\s+/);
for(var i=0;i<bits.length;i++) if(POS_SET.has(bits[i].toUpperCase())) return false;
return true;
}
function scrapeRequirements(){
var cands=[],els=document.querySelectorAll('div,span,li,p,td,dt,dd,h1,h2,h3,h4,label');
for(var i=0;i<els.length;i++){
var el=els[i];
if(el.children.length>3) continue;                 // leaves, not containers
var t=(el.textContent||'').replace(/\s+/g,' ').trim();
if(looksLikeRequirement(t)) cands.push({el:el,text:t});
}
if(!cands.length) return [];
var tally=[],nodes=[];
for(var c=0;c<cands.length;c++){
var a=cands[c].el;
for(var up=0; up<5 && a && a!==document.body; up++, a=a.parentElement){
var idx=nodes.indexOf(a);
if(idx<0){ nodes.push(a); tally.push(1); } else tally[idx]++;
}
}
var best=null,bestN=0;
for(var k=0;k<nodes.length;k++){
if(tally[k]>bestN || (tally[k]===bestN && best && nodes[k].querySelectorAll('*').length<best.querySelectorAll('*').length)){
bestN=tally[k]; best=nodes[k];
}
}
var out=[],seen={};
for(var m=0;m<cands.length;m++){
if(best && !best.contains(cands[m].el)) continue;
if(seen[cands[m].text]) continue;
seen[cands[m].text]=1; out.push(cands[m].text);
}
return out;
}
function detectFormation(){
var t=(document.body.innerText||'').replace(/\s+/g,' ');
for(var i=0;i<E.FORMATIONS.length;i++){
var f=E.FORMATIONS[i];
if(new RegExp('(^|[^\\d-])'+f.name.replace(/-/g,'\\-')+'([^\\d-]|$)').test(t)) return i;
}
return 1; // 4-3-3
}
var host=document.createElement('div');
host.id='sbc-autopilot-host';
host.style.cssText='position:fixed;top:70px;right:18px;z-index:2147483647;width:360px;max-width:calc(100vw - 24px)';
var root=host.attachShadow?host.attachShadow({mode:'open'}):host; // shadow DOM keeps EA's CSS out
document.documentElement.appendChild(host);
var CSS='\
:host,*{box-sizing:border-box}\
.p{font:13px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;background:#0d1119;color:#eef2f8;border:1px solid #2b3648;border-radius:14px;box-shadow:0 20px 60px rgba(0,0,0,.6);overflow:hidden}\
.h{display:flex;align-items:center;gap:8px;padding:10px 12px;background:#131926;border-bottom:1px solid #1e2735;cursor:move;user-select:none}\
.h b{font-size:12px;letter-spacing:.12em;text-transform:uppercase;flex:1}\
.h .dot{width:8px;height:8px;border-radius:50%;background:#00e07a}\
.h button{background:none;border:1px solid #2b3648;color:#8d97ab;width:22px;height:22px;border-radius:6px;cursor:pointer;font-size:12px;line-height:1;padding:0}\
.h button:hover{color:#eef2f8;border-color:#00e07a}\
.b{padding:12px;max-height:70vh;overflow:auto}\
.p.min .b{display:none}\
.s{margin-bottom:12px;padding-bottom:12px;border-bottom:1px solid #1e2735}\
.s:last-child{margin-bottom:0;padding-bottom:0;border-bottom:none}\
.t{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#8d97ab;margin-bottom:7px;font-weight:700}\
button.a{background:#00e07a;color:#04150d;border:none;border-radius:8px;padding:8px 12px;font-weight:700;font-size:12px;cursor:pointer;font-family:inherit}\
button.a:hover{background:#00b863}\
button.a:disabled{opacity:.45;cursor:not-allowed}\
button.g{background:#131926;color:#eef2f8;border:1px solid #2b3648;border-radius:8px;padding:7px 11px;font-size:12px;cursor:pointer;font-family:inherit}\
button.g:hover{border-color:#00e07a;color:#00e07a}\
button.on{background:#07281c;border-color:#00e07a;color:#00e07a}\
.row{display:flex;gap:6px;flex-wrap:wrap;align-items:center}\
.st{font-size:11px;color:#8d97ab;margin-top:7px;line-height:1.5}\
.st b{color:#eef2f8}\
.warn{color:#ffb020}\
.bad{color:#ff5a5a}\
.good{color:#00e07a}\
textarea{width:100%;min-height:86px;background:#080b12;color:#eef2f8;border:1px solid #2b3648;border-radius:8px;padding:7px;font:11px/1.5 ui-monospace,Menlo,monospace;resize:vertical}\
select{background:#131926;color:#eef2f8;border:1px solid #2b3648;border-radius:7px;padding:5px 7px;font-size:11px;font-family:inherit}\
.pr{height:5px;background:#1a2233;border-radius:9px;overflow:hidden;margin-top:8px;display:none}\
.pr.on{display:block}.pr i{display:block;height:100%;width:0;background:#00e07a}\
table{width:100%;border-collapse:collapse;font-size:11px;margin-top:8px}\
td{padding:4px 5px;border-bottom:1px solid #1e2735;vertical-align:top}\
td.sl{font:700 10px ui-monospace,monospace;color:#8d97ab;white-space:nowrap}\
td.ov{font-weight:700;color:#f5c451;width:22px}\
td.ch{text-align:right;color:#8d97ab;white-space:nowrap}\
.oop{color:#ff5a5a}\
.cl{display:flex;gap:7px;font-size:11px;padding:3px 0}\
.cl i{font-style:normal;font-weight:700;width:30px}\
.note{font-size:10px;color:#5d6779;margin-top:8px;line-height:1.5}';
var wrap=document.createElement('div');
wrap.innerHTML='<style>'+CSS+'</style>\
<div class="p" id="panel">\
<div class="h" id="drag"><span class="dot"></span><b>SBC Autopilot</b>\
<button id="min" title="Minimise">–</button><button id="cls" title="Close">×</button></div>\
<div class="b">\
<div class="s">\
<div class="t">1 · Your club</div>\
<div class="row"><button class="g" id="harv">Start harvesting</button><button class="g" id="copyClub">Copy club</button><button class="g" id="clr">Clear</button></div>\
<div class="st" id="clubSt">Turn harvesting on, then scroll through your club so every player renders.</div>\
</div>\
<div class="s">\
<div class="t">2 · The SBC on screen</div>\
<div class="row"><button class="g" id="read">Read requirements</button></div>\
<textarea id="sbcTxt" placeholder="Open an SBC, then hit Read requirements. Edit anything it gets wrong."></textarea>\
<div class="st" id="sbcSt">Nothing read yet.</div>\
</div>\
<div class="s">\
<div class="t">3 · Solve</div>\
<div class="row"><select id="form"></select><select id="eff">\
<option value="fast">Fast</option><option value="deep" selected>Deep</option><option value="max">Exhaustive</option></select>\
<button class="a" id="solve">Solve</button></div>\
<div class="pr" id="pr"><i></i></div>\
<div class="st" id="solveSt">Harvest a club and read an SBC first.</div>\
</div>\
<div class="s" id="resWrap" style="display:none">\
<div class="t">4 · Build this</div>\
<div id="res"></div>\
<div class="row" style="margin-top:9px"><button class="g" id="copyRes">Copy squad</button></div>\
</div>\
<div class="note">Values are estimated from rating — the web app shows no prices and this tool makes no network calls. It reads the page and nothing else: no clicking, no submitting, nothing sent anywhere. Unofficial, not affiliated with EA.</div>\
</div>\
</div>';
root.appendChild(wrap);
var $=function(s){ return root.getElementById?root.getElementById(s):wrap.querySelector('#'+s); };
var store={list:[],byKey:{}}, reqs=[], lastRes=null, harvesting=false, timer=null, obs=null, solving=false;
function clubStatus(){
var n=store.list.length;
if(!n){ $('clubSt').innerHTML='Turn harvesting on, then scroll through your club so every player renders.'; return; }
var withClub=0,withLeague=0,withNation=0,rare=0;
for(var i=0;i<n;i++){ var p=store.list[i];
if(p.club)withClub++; if(p.league)withLeague++; if(p.nation)withNation++; if(p.rare)rare++; }
var chemOk=(withClub+withLeague+withNation)/(n*3);
$('clubSt').innerHTML='<b>'+n+'</b> players · club '+withClub+' · league '+withLeague+' · nation '+withNation+' · looked rare '+rare+
(chemOk<0.6?'<br><span class="warn">Chemistry data is patchy — crest/flag images were not recognised, so chemistry rules may be wrong.</span>':'');
}
function setHarvest(on){
harvesting=on;
var b=$('harv');
b.textContent=on?'Harvesting… (stop)':'Start harvesting';
b.className=on?'g on':'g';
if(on){
var sweep=function(){ last=Date.now(); var r=harvestOnce(store); if(r.added) clubStatus(); };
var last=0,pending=null;
var schedule=function(){
var wait=250-(Date.now()-last);
if(wait<=0){ if(pending){clearTimeout(pending);pending=null;} sweep(); }
else if(!pending) pending=setTimeout(function(){ pending=null; sweep(); },wait);
};
sweep();
timer=setInterval(sweep,700);
if(window.MutationObserver){
obs=new MutationObserver(schedule);
obs.observe(document.body,{childList:true,subtree:true});
obs._clear=function(){ if(pending) clearTimeout(pending); };
}
} else {
clearInterval(timer); timer=null;
if(obs){ obs.disconnect(); if(obs._clear) obs._clear(); obs=null; }
}
clubStatus();
}
$('harv').onclick=function(){ setHarvest(!harvesting); };
$('clr').onclick=function(){ store={list:[],byKey:{}}; clubStatus(); };
$('copyClub').onclick=function(){
var lines=['name\trating\tpos\tnation\tleague\tclub\tprice\ttags'];
for(var i=0;i<store.list.length;i++){ var p=store.list[i];
lines.push([p.name,p.rating,p.pos.join('/'),p.nation,p.league,p.club,p.price,
[p.icon?'icon':'',p.hero?'hero':'',p.special?'totw':'',p.rare?'rare':'',p.untradeable?'untradeable':''].filter(Boolean).join(' ')].join('\t'));
}
copy(lines.join('\n'),'Club copied — paste it into the solver page');
};
function reparse(){
var out=E.parseSbc($('sbcTxt').value,store.list);
reqs=out.reqs;
var names=[];
for(var i=0;i<reqs.length;i++) names.push(E.reqLabel(reqs[i]));
$('sbcSt').innerHTML=reqs.length
? '<span class="good">'+reqs.length+' rule(s):</span> '+names.join(' · ')+(out.unparsed.length?'<br><span class="warn">Ignored '+out.unparsed.length+' line(s).</span>':'')
: '<span class="warn">No rules recognised — type them in, e.g. "Squad Rating: Min. 84".</span>';
}
$('read').onclick=function(){
var lines=scrapeRequirements();
$('sbcTxt').value=lines.join('\n');
reparse();
if(!lines.length) $('sbcSt').innerHTML='<span class="bad">Found nothing on screen — open the SBC\'s requirements panel, or type them in.</span>';
};
$('sbcTxt').oninput=function(){ clearTimeout(reparse._t); reparse._t=setTimeout(reparse,250); };
var fsel=$('form'),fopt='';
for(var i=0;i<E.FORMATIONS.length;i++) fopt+='<option value="'+i+'">'+E.FORMATIONS[i].name+'</option>';
fsel.innerHTML=fopt;
fsel.value=String(detectFormation());
$('solve').onclick=function(){
if(solving) return;
if(store.list.length<11){ $('solveSt').innerHTML='<span class="bad">Only '+store.list.length+' players harvested — need at least 11.</span>'; return; }
var formation=E.FORMATIONS[+fsel.value]||E.FORMATIONS[1];
var opts={relPos:true,safe:false,excludeIcons:false,untradeMul:1,effort:$('eff').value};
solving=true; $('solve').disabled=true; $('pr').className='pr on'; $('pr').firstChild.style.width='0%';
$('solveSt').textContent='Searching…';
E.solveAsync(store.list,reqs,formation,opts,
function(pct){ $('pr').firstChild.style.width=Math.round(pct*100)+'%'; },
function(out){
solving=false; $('solve').disabled=false; $('pr').className='pr';
if(out.error){ $('solveSt').innerHTML='<span class="bad">'+out.error+'</span>'; return; }
render(out.best,formation);
});
};
function render(res,formation){
lastRes=res; lastRes.formation=formation;
var ev=res.ev, det=ev.chem.detail.slice().sort(function(a,b){ return a.slotIndex-b.slotIndex; });
var allPass=true; for(var i=0;i<ev.checks.length;i++) if(!ev.checks[i].pass) allPass=false;
var h='<div class="st"><b>'+formation.name+'</b> · rating <b>'+ev.rating.rating+'</b> ('+ev.rating.exact.toFixed(2)+
') · chem <b>'+ev.chem.total+'</b>/33 · est. value <b>'+E.coins(res.cost)+'</b></div><table>';
for(var j=0;j<det.length;j++){ var d=det[j];
h+='<tr><td class="sl'+(d.inPos?'':' oop')+'">'+d.slot+(d.inPos?'':' ⚠')+'</td><td class="ov">'+d.player.rating+
'</td><td>'+esc(d.player.name)+'</td><td class="ch">'+d.chem+'/3</td></tr>';
}
h+='</table>';
for(var k=0;k<ev.checks.length;k++){ var c=ev.checks[k];
h+='<div class="cl"><i class="'+(c.pass?'good':'bad')+'">'+(c.pass?'PASS':'FAIL')+'</i><span>'+esc(E.reqLabel(c.req))+' — you have '+c.actual+'</span></div>';
}
if(!allPass) h+='<div class="st bad">Some rules are still short — this is the closest it found.</div>';
$('res').innerHTML=h;
$('resWrap').style.display='';
$('solveSt').innerHTML=allPass?'<span class="good">Solved — every rule met.</span>':'<span class="warn">Closest squad shown.</span>';
}
$('copyRes').onclick=function(){
if(!lastRes) return;
var det=lastRes.ev.chem.detail.slice().sort(function(a,b){ return a.slotIndex-b.slotIndex; }),out=[];
out.push('SBC squad — '+lastRes.formation.name+'  ·  rating '+lastRes.ev.rating.rating+'  ·  chem '+lastRes.ev.chem.total+'/33');
for(var i=0;i<det.length;i++) out.push(pad(det[i].slot,5)+pad(String(det[i].player.rating),4)+det[i].player.name+(det[i].inPos?'':'   (out of position)'));
copy(out.join('\n'),'Squad copied');
};
function pad(s,n){ while(s.length<n) s+=' '; return s; }
function esc(s){ return String(s).replace(/[&<>"]/g,function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]; }); }
function copy(text,msg){
var done=function(){ var el=$('solveSt'); var old=el.innerHTML; el.innerHTML='<span class="good">'+msg+'</span>'; setTimeout(function(){ el.innerHTML=old; },1800); };
if(navigator.clipboard&&navigator.clipboard.writeText){ navigator.clipboard.writeText(text).then(done,fallback); }
else fallback();
function fallback(){
var ta=document.createElement('textarea');
ta.value=text; ta.style.cssText='position:fixed;top:-2000px';
document.body.appendChild(ta); ta.select();
try{ document.execCommand('copy'); done(); }catch(e){ alert(text); }
document.body.removeChild(ta);
}
}
(function(){
var d=$('drag'),sx=0,sy=0,ox=0,oy=0,on=false;
d.addEventListener('mousedown',function(e){
if(e.target.tagName==='BUTTON') return;
on=true; sx=e.clientX; sy=e.clientY;
var r=host.getBoundingClientRect(); ox=r.left; oy=r.top;
e.preventDefault();
});
window.addEventListener('mousemove',function(e){
if(!on) return;
host.style.left=(ox+e.clientX-sx)+'px';
host.style.top=(oy+e.clientY-sy)+'px';
host.style.right='auto';
});
window.addEventListener('mouseup',function(){ on=false; });
})();
$('min').onclick=function(){ var p=$('panel'); p.className=p.className.indexOf('min')<0?'p min':'p'; };
$('cls').onclick=function(){ setHarvest(false); host.remove(); window.__SBC_PILOT__=null; };
window.__SBC_PILOT__={
toggle:function(){ host.style.display=host.style.display==='none'?'':'none'; },
store:store
};
clubStatus();
})();
})();
